export const MEDIA_FLAVOR_TEXTS: Record<string, string[]> = {
  Game: [
    "Just one more turn.",
    "Rolling for initiative.",
    "Praising the sun.",
    "Press F to pay respects.",
    "The cake is a lie.",
    "It's dangerous to go alone.",
    "Wasted.",
    "You died.",
    "Finish him!",
    "Do you guys not have phones?",
    "Hey, you, you're finally awake.",
    "Would you kindly?",
    "War. War never changes.",
    "I used to be an adventurer like you.",
    "A winner is you!",
    "It's a-me!",
    "Snake? Snake?! SNAAAAKE!",
    "Nothing is true, everything is permitted.",
    "I need a weapon.",
    "Pootis.",
    "Rip and tear, until it is done.",
    "Get over here!",
    "Our princess is in another castle.",
    "Boy.",
    "Stay awhile and listen.",
    "All your base are belong to us.",
    "Do a barrel roll!",
    "Thank you Dark Souls.",
    "FUS RO DAH!",
    "What is a man? A miserable little pile of secrets.",
    "I survived the Gulag.",
    "They played us like a damn fiddle!",
    "Sir, finishing this bite.",
    "I'm Commander Shepard, and this is my favorite store.",
    "Waka waka waka.",
    "Look behind you, a three-headed monkey!",
    "The right man in the wrong place can make all the difference.",
    "You have died of dysentery.",
    "Rise and shine, Mr. Freeman.",
    "No gods or kings, only man.",
    "I am Error.",
    "A delayed game is eventually good.",
    "This was a triumph.",
    "Keep your expectations low.",
    "You must construct additional pylons.",
    "Zug zug.",
    "Work complete.",
    "Leeroy Jenkins!",
    "Time to kick ass and chew bubble gum.",
    "What are you buying?"
  ],
  Book: [
    "Just one more chapter.",
    "The smell of old paper.",
    "So many books, so little time.",
    "Don't judge a book by its movie.",
    "It was the best of times, it was the worst of times.",
    "Call me Ishmael.",
    "In a hole in the ground there lived a hobbit.",
    "Reader, I married him.",
    "The man in black fled across the desert.",
    "All children, except one, grow up.",
    "It is a truth universally acknowledged.",
    "Happy families are all alike.",
    "I am haunted by humans.",
    "There is no greater agony than bearing an untold story.",
    "A room without books is like a body without a soul.",
    "Fahrenheit 451: The temperature at which book paper catches fire.",
    "Big Brother is watching you.",
    "Not all those who wander are lost.",
    "To be or not to be.",
    "Frankly, my dear, I don't give a damn.",
    "TBR pile acting as a structural support.",
    "Running out of shelf space.",
    "Bought a book but haven't read the last three I bought.",
    "I read therefore I am.",
    "Words are our most inexhaustible source of magic.",
    "A mind needs books as a sword needs a whetstone.",
    "Just reading the synopsis.",
    "Ah, a plot twist...",
    "Why'd they have to kill off my favorite character?",
    "Book hangover in progress.",
    "Adding to my Goodreads right now.",
    "Papercut survivor.",
    "I'm not ignoring you, I'm just somewhere else.",
    "Reality is entirely too literal for me.",
    "Reading: because reality is overrated.",
    "Where did I leave my bookmark?",
    "Dog-earing pages is a crime.",
    "Smelling the spine.",
    "Another fantasy trilogy? Put it on my tab.",
    "Who needs sleep when there are books?",
    "Hardcover, paperback, or e-book?",
    "I have lived a thousand lives.",
    "Lost in the library.",
    "Dust jackets are my aesthetic.",
    "Words, words, words.",
    "The pen is mightier than the sword.",
    "Between the lines.",
    "Reading under the covers with a flashlight.",
    "Chapter One: The Beginning.",
    "The Epilogue is rarely the end."
  ],
  Audiobook: [
    "Listening at 2x speed.",
    "The narrator's voice is so soothing.",
    "Whispersync engaged.",
    "I 'read' it.",
    "Perfect for the commute.",
    "Washing dishes while consuming epic fantasy.",
    "Who needs music?",
    "Narrator does all the voices.",
    "Wait, let me rewind 30 seconds.",
    "Fell asleep, where was I?",
    "Bluetooth connected.",
    "Can't hear you, currently fighting a dragon.",
    "The ultimate multitasking tool.",
    "Listening at 1.5x speed is the optimal way.",
    "Earbuds locked in.",
    "Letting someone else do the reading.",
    "The storytelling campfire.",
    "My eyes are resting, my brain is zooming.",
    "Audiobooks count as reading.",
    "Volume up, world down.",
    "The narrator made me cry.",
    "Waiting for the next credit.",
    "It's like a movie for your ears.",
    "Just 10 more minutes on this drive.",
    "This voice actor is a legend.",
    "I can't pause, it's the climax!",
    "Hearing the characters come alive.",
    "Zoned out for a second, got to rewind.",
    "An entire library in my pocket.",
    "Is it unabridged?",
    "Chapters by track number.",
    "Slower... no, faster...",
    "Perfect for pacing around the house.",
    "The audiobook is better.",
    "Hearing the author's note.",
    "Voice of an angel, plot of a demon.",
    "Immersive audio design.",
    "Auditory hallucination.",
    "Running errands in another universe.",
    "Closing my eyes to see the story.",
    "Listening while staring blankly at the wall.",
    "The golden age of radio, but better.",
    "Ear comfort level: Maximum.",
    "Why read when you can listen?",
    "Please don't interrupt the story.",
    "My favorite background noise.",
    "Soundtrack to my chores.",
    "Pacing my walk to the narrator's rhythm.",
    "Words entering directly into the brain.",
    "The voice inside my head isn't mine right now."
  ],
  "Visual Novel": [
    "Clicking through the dialogue.",
    "Saving before the choice.",
    "Doki doki.",
    "Tsundere incoming.",
    "Route unlocked.",
    "Just Monika.",
    "Reading at the speed of light.",
    "Skipping the text I've already read.",
    "Bad end.",
    "True end unlocked.",
    "Hold Ctrl to skip.",
    "Wait, let me load my save.",
    "Which heroine to pick?",
    "Auto-play mode engaged.",
    "The elusive good ending.",
    "I object!",
    "Hope, despair, and reading.",
    "This BGM goes hard.",
    "Text box transparency: 50%.",
    "Selecting the right dialogue option.",
    "Voice acting fully voiced.",
    "CG gallery completion 100%.",
    "Crying over 2D characters.",
    "A kinetic novel experience.",
    "It's not just a game, it's literature.",
    "Looking up a walkthrough.",
    "I need to view every single timeline.",
    "Who left these onions here?",
    "Another slice of life.",
    "Suddenly, plot twist.",
    "I didn't expect to cry today.",
    "The UI is so clean.",
    "Waiting for the translation patch.",
    "Reading is playing too.",
    "Is there a secret route?",
    "Loading... 99%.",
    "Where is the skip unread button?",
    "Every choice matters. Or does it?",
    "Taking screenshots of every CG.",
    "Best girl.",
    "Best boy.",
    "The protagonist has no eyes.",
    "Childhood friend vs the transfer student.",
    "I'm here for the plot.",
    "I'm here for the 'plot'.",
    "Kinetic typography.",
    "A story told in text and sprites.",
    "The backlog is my best friend.",
    "Who is the mastermind?",
    "Endless eight flashbacks."
  ],
  Manga: [
    "Reading right to left.",
    "Next chapter next week.",
    "Is it on hiatus again?",
    "Omae wa mou shindeiru.",
    "I am the bone of my sword.",
    "I will become the Pirate King!",
    "Equivalent exchange.",
    "Plus Ultra!",
    "It's over 9000!",
    "Bankai.",
    "Domain Expansion.",
    "Yare yare daze.",
    "Just one more chapter before bed.",
    "Waiting for the translation.",
    "The anime didn't do this justice.",
    "Black and white, but full of emotion.",
    "Double page spread glory.",
    "Shonen power scaling.",
    "Shojo bubbles.",
    "Another isekai?",
    "Truck-kun strikes again.",
    "Tournament arc!",
    "Tsundere pout.",
    "The power of friendship.",
    "Reading the raw scans.",
    "Author's note: I caught a cold.",
    "My manga backlog is crying.",
    "Reading on my tablet.",
    "Panel by panel.",
    "Sound effect: *DOOM*",
    "I relate to the villain now.",
    "Beach episode when?",
    "The manga was better.",
    "Looking for the anime adaptation.",
    "Reading in the dark.",
    "Where is volume 3?!",
    "I love the art style.",
    "The detailed backgrounds.",
    "Who needs sleep when there's manga?",
    "Binge-reading 100 chapters.",
    "That cliffhanger!",
    "Waiting monthly is suffering.",
    "Gotta catch 'em all.",
    "Believe it!",
    "Senpai noticed me.",
    "NANI?!",
    "Kamehameha!",
    "Gomu Gomu no...",
    "I'll take a potato chip... and eat it!",
    "The training arc begins."
  ],
  Series: [
    "Just one more episode.",
    "Skipping the intro.",
    "Are you still watching?",
    "The binge is real.",
    "Winter is coming.",
    "Bazinga.",
    "I am the one who knocks.",
    "Pivot!",
    "How you doin'?",
    "That's what she said.",
    "Did you see the latest episode?",
    "Spoilers ahead.",
    "Season finale.",
    "Canceled after one season.",
    "I've seen this episode 10 times.",
    "The book was better, but the show is good.",
    "Waiting for the next season.",
    "Pilot was weak, but it gets better.",
    "Filler episode.",
    "Previously on...",
    "To be continued...",
    "I paused it, hurry up.",
    "Popcorn is ready.",
    "I need subtitles for this.",
    "Don't talk during the show.",
    "The theme song is stuck in my head.",
    "Who is your favorite character?",
    "I ship them.",
    "Another streaming service?",
    "Watching at 1.5x speed.",
    "I only watch for the plot.",
    "The cliffhanger was illegal.",
    "Can't stop, won't stop.",
    "A recap? Skip.",
    "Wait, who is that guy again?",
    "Let's binge watch it this weekend.",
    "I need a new show to watch.",
    "Rewatching my comfort show.",
    "This season is a letdown.",
    "The writing is so good.",
    "I didn't see that coming.",
    "Six seasons and a movie.",
    "D'oh!",
    "Wubba lubba dub dub!",
    "The truth is out there.",
    "Trust no one.",
    "I'll be there for you.",
    "Live long and prosper.",
    "Make it so.",
    "This is the way."
  ],
  Movie: [
    "Get the popcorn.",
    "I am your father.",
    "May the Force be with you.",
    "I'll be back.",
    "Here's looking at you, kid.",
    "You're gonna need a bigger boat.",
    "I feel the need - the need for speed.",
    "To infinity and beyond!",
    "There's no place like home.",
    "I see dead people.",
    "Why so serious?",
    "My precious.",
    "Director's cut.",
    "Post-credits scene.",
    "The sequel was worse.",
    "Wait, is this a reboot?",
    "Action, camera, lights!",
    "The cinematic universe.",
    "Pass the 3D glasses.",
    "I sneaked snacks in.",
    "Shhh, it's starting.",
    "The CGI has not aged well.",
    "Oscar bait.",
    "A visual masterpiece.",
    "The soundtrack is epic.",
    "Did you catch that easter egg?",
    "I cried during the intro.",
    "Best villain ever.",
    "The twist was obvious.",
    "I am Iron Man.",
    "Avengers, assemble.",
    "Hasta la vista, baby.",
    "You can't handle the truth!",
    "E.T. phone home.",
    "Bond. James Bond.",
    "I'm king of the world!",
    "Life is like a box of chocolates.",
    "Yippee-ki-yay.",
    "I love the smell of napalm in the morning.",
    "Say hello to my little friend.",
    "I'm gonna make him an offer he can't refuse.",
    "Here's Johnny!",
    "You talking to me?",
    "Houston, we have a problem.",
    "Keep your friends close, but your enemies closer.",
    "A boy's best friend is his mother.",
    "Nobody puts Baby in a corner.",
    "I'll have what she's having.",
    "We're not in Kansas anymore.",
    "Frankly my dear."
  ],
  Comic: [
    "POW! BAM! THWACK!",
    "With great power comes great responsibility.",
    "I am vengeance. I am the night.",
    "Up, up, and away!",
    "Avengers Assemble!",
    "It's clobberin' time!",
    "Hulk smash!",
    "Snikt!",
    "Bamf!",
    "Thwip!",
    "Waiting for the trade paperback.",
    "I need a bag and board for this.",
    "Near mint condition.",
    "First appearance.",
    "Variant cover.",
    "The multiverse is expanding.",
    "Crisis on Infinite Earths.",
    "Into the Spider-Verse.",
    "Is this canon?",
    "The coloring is phenomenal.",
    "Speech bubbles everywhere.",
    "To be continued in issue #42.",
    "Crossover event of the century.",
    "Who is the secret identity?",
    "Another reboot?",
    "Graphic novels are literature.",
    "Inking the lines.",
    "The panels flow so well.",
    "Reading the omnibuses.",
    "My pull list is too long.",
    "Back issue bin diving.",
    "Stan Lee cameo.",
    "Excelsior!",
    "Make mine Marvel.",
    "DC vs Marvel.",
    "I love independent comics.",
    "Webtoons count too.",
    "Scroll down for the next panel.",
    "Daily strip vibes.",
    "The golden age.",
    "Silver age silliness.",
    "Modern age grit.",
    "It's a bird! It's a plane!",
    "I'm the best there is at what I do.",
    "By the hoary hosts of Hoggoth!",
    "Shazam!",
    "Flame on!",
    "In brightest day, in blackest night.",
    "I am Groot.",
    "Maximum effort."
  ]
};

// Media-specific expansion templates to ensure thematic variety
const THEMATIC_EXPANSIONS: Record<string, string[]> = {
  Game: [
    "Achievement unlocked: Vault Dweller.",
    "Inventory expanding to accommodate more loot.",
    "The meta is shifting in favor of your collection.",
    "Patch notes: Added more adventures to the backlog.",
    "Your save file size is reaching legendary proportions.",
    "No microtransactions here, just pure progress.",
    "Frame rates may vary, but the quality is consistent.",
    "Quick-saving your progress through the years.",
    "The RNG gods smile upon this entry.",
    "Wait, is this a secret level?",
    "A legendary drop in the sea of titles.",
    "Min-maxing your media consumption.",
    "The difficulty curve of your backlog is steep.",
    "Equipping the 'Lorekeeper' title for a +10 wisdom buff.",
    "Ganking the boredom with another logged title.",
    "Your K/D ratio on finishing games is improving.",
    "Exploring every corner of the digital map.",
    "The console is warm, the coffee is hot.",
    "Zero deaths. (Probably).",
    "Loading new textures for your gaming history.",
    "Easter egg found in the metadata.",
    "Speedrunning through your childhood favorites.",
    "The platinum trophy is within reach.",
    "A wild media entry appears!",
    "It's not a bug, it's a feature of your library.",
    "Grinding for that 100% completion mark.",
    "The final boss of backlogs awaits.",
    "Mana restored. Time to play.",
    "Your gaming legacy is being written in code.",
    "Press Start to continue the collection."
  ],
  Book: [
    "Library capacity increased by another shelf.",
    "Drafting the ultimate bibliography of your life.",
    "The ink never fades in the vault of memories.",
    "A paper trail that leads to enlightenment.",
    "Between the covers lies a world of data.",
    "The spine of this collection is unbroken.",
    "Footnotes for a life well-read.",
    "The margins of your history are full of notes.",
    "Literary prestige reaching critical mass.",
    "A binding that holds a thousand dreams.",
    "Dust jackets preserved for the next century.",
    "The typography of your soul is Serif.",
    "Chronicles of a dedicated wordsmith.",
    "The library is silent, but the stories are loud.",
    "Scribing another entry into the master scroll.",
    "From pulp fiction to high literature.",
    "A prose that defines your journey.",
    "The scent of vanilla and old wisdom.",
    "Hardcovers for the heavy hitters.",
    "Softcovers for the light sleepers.",
    "A bookmark left in the annals of time.",
    "The narrative arc of your life is peaking.",
    "Metaphors for every mood in this collection.",
    "Similes as numerous as the pages themselves.",
    "The plot thickens with every new addition.",
    "An anthology of a true Lorekeeper.",
    "Signed editions of your favorite memories.",
    "The library card is full.",
    "Returning to the classics once more.",
    "A literary sanctuary for the weary mind."
  ],
  Audiobook: [
    "Audio bitrate: Maximum quality vibes.",
    "The frequency of your listening is increasing.",
    "Stereo-typical behavior for an audiophile.",
    "A soundstage for your imagination.",
    "Noise-canceling the outside world.",
    "The vibrations of a thousand stories.",
    "Ears tuned to the frequency of lore.",
    "A symphony of spoken words.",
    "The narrator is your guide through the abyss.",
    "Auditory processing at 200% capacity.",
    "The volume of this collection is quite loud.",
    "A podcast? No, this is art.",
    "Sonic waves of narrative excellence.",
    "The headphones are an extension of the soul.",
    "Listening between the soundwaves.",
    "The acoustic property of this Vault is 'Perfect'.",
    "Wireless connection to the heart of the story.",
    "The rhythm of the narrator's breath.",
    "A performance that echoes in the mind.",
    "The sound of silence is for people without audiobooks.",
    "Echoing through the chambers of the vault.",
    "A resonant frequency of high-quality lore.",
    "The decibels of your dedication.",
    "Amplify your understanding of the world.",
    "Signal-to-noise ratio is incredibly high here.",
    "The EQ is set to 'Epic'.",
    "Surround sound for the solitary listener.",
    "The bass drops when the plot twist hits.",
    "An auditory archive of excellence.",
    "Tuning in to the latest chapter."
  ],
  "Visual Novel": [
    "Sprites aligned, backgrounds rendered.",
    "CG gallery completion increased.",
    "A multi-choice path to the ultimate vault.",
    "The script is longer than most novels.",
    "Wait, is this the route I wanted?",
    "Every click is a step toward the truth.",
    "The visual fidelity of your memories.",
    "Transitions as smooth as the narrative.",
    "A story told in frames and feelings.",
    "Does this dialogue choice affect the meta?",
    "Scanning for the 'True Ending' of your backlog.",
    "The auto-save function of a life well-read.",
    "A kinetic experience for a static moment.",
    "The UI of your life is getting an upgrade.",
    "A world of heroines and high stakes.",
    "The protagonist's internal monologue is yours.",
    "A visual symphony of text and light.",
    "The backlog route is the hardest one.",
    "Unlocking the 'Lorekeeper' ending.",
    "The sprites are blushing.",
    "A choice that changed everything.",
    "The soundtrack changes with the mood.",
    "A visual feast for the narrative-hungry.",
    "The resolution of your dedication.",
    "A pixel-perfect archive of stories.",
    "The text box is full of secrets.",
    "Scanning the script for hidden meanings.",
    "A visual journey through the digital pages.",
    "The choices we make in 2D.",
    "A novel approach to visual storytelling."
  ],
  Manga: [
    "Scanning the inks for artistic intent.",
    "The screentone of your history is iconic.",
    "A panel-by-panel breakdown of your growth.",
    "The lineart of your life is incredibly clean.",
    "Drafting the storyboards for future entries.",
    "Tankobon tracking engaged.",
    "The speedlines of your dedication.",
    "A splash page of your greatest achievements.",
    "The gutters between stories are full of mystery.",
    "Serialized excellence in every entry.",
    "Mangaka-level effort in the collection.",
    "The ink is still wet on the latest log.",
    "A world in black, white, and grey matter.",
    "Shonen spirit, Shojo heart.",
    "The Seinen depth of your collection.",
    "A Josei journey of growth.",
    "The manga is definitely better than the live-action.",
    "Scaling the heights of the latest arc.",
    "A character design that speaks volumes.",
    "The evolution of art over a thousand chapters.",
    "Wait, is that a redraw?",
    "Looking for the hidden omake.",
    "A monthly release of pure quality.",
    "The weekly grind for that one chapter.",
    "An anthology of artistic brilliance.",
    "The ink density is off the charts.",
    "A visual shorthand for 'Obsessed'.",
    "The paneling leads directly to the vault.",
    "A masterpiece of sequential art.",
    "The spirit of the mangaka is within you."
  ],
  Series: [
    "Binge-watching your own history.",
    "Season renewal: Guaranteed.",
    "The plot armor of your collection is thick.",
    "A crossover episode of all your favorites.",
    "The series finale is nowhere in sight.",
    "Streaming excellence directly to the vault.",
    "The production value of your backlog is high.",
    "A cliffhanger at every turn.",
    "Character development: Significant.",
    "The pilot episode was just the beginning.",
    "A syndicated success STORY.",
    "The ratings for your collection are 5 stars.",
    "A spin-off of a life well-lived.",
    "The showrunners of the universe are impressed.",
    "A cinematic experience on the small screen.",
    "Wait, is there a post-credits scene?",
    "The opening credits are iconic.",
    "Closing credits: See you next time.",
    "A cast of characters you'll never forget.",
    "The script doctoring of your memories.",
    "A multi-cam setup for your daily logs.",
    "The lighting in this series is perfect.",
    "A world-building masterclass.",
    "The lore of this show is deep.",
    "A bingeable collection of entries.",
    "The television is always on in the mind.",
    "A broadcast of pure dedication.",
    "The remote is in your hands.",
    "Channel surfing for the next big story.",
    "A television landmark in your collection."
  ],
  Movie: [
    "A double feature of greatness.",
    "Casting for the movie of your life.",
    "The box office numbers for this vault are huge.",
    "A cinematic masterpiece logged.",
    "The director's cut of your memories.",
    "Wait, is that a lens flare?",
    "The cinematography of your dedication.",
    "A blockbuster entry in the library.",
    "The red carpet is rolled out for you.",
    "An indie darling of a collection.",
    "The color grading of your history is vibrant.",
    "A visual effects extravaganza.",
    "The sound design is Oscar-worthy.",
    "A screenplay written in the stars.",
    "The editing is incredibly tight.",
    "A feature-length log of excellence.",
    "Wait, I missed that detail. Rewind.",
    "The silver screen reflects your soul.",
    "A cinematic universe of your own making.",
    "The popcorn is buttery, the movie is epic.",
    "A wide-angle shot of the whole vault.",
    "The aspect ratio is perfect.",
    "A 35mm archive of excellence.",
    "Digital projection of pure lore.",
    "The trailer was just a glimpse.",
    "The premiere of your latest favorite.",
    "A cinematic landmark logged.",
    "The film is processing.",
    "A shot for the ages.",
    "The end credits roll, but the story stays."
  ],
  Comic: [
    "Multiverse exploration: Successful.",
    "A variant cover for every day.",
    "The continuity of your collection is flawless.",
    "A retcon that actually makes sense.",
    "The superpowers of a dedicated reader.",
    "A secret lair full of long-boxes.",
    "The ink and colors of your history.",
    "A graphic novel for the ages.",
    "Wait, is this a limited series?",
    "The crossover event you've been waiting for.",
    "A legendary first issue in the collection.",
    "The panels of time are ticking away.",
    "A hero's journey in every issue.",
    "The villain's monologue was actually quite long.",
    "A cape and mask for the Lorekeeper.",
    "The city is safe, the comics are read.",
    "A comic shop in the heart of the vault.",
    "The printing quality is superb.",
    "Wait, I found a hidden Stan Lee cameo.",
    "The source material for your imagination.",
    "A visual shorthand for 'Encyclopedia'.",
    "The lettering is incredibly legible.",
    "A splash of color in a grey world.",
    "The evolution of the medium on your shelf.",
    "A sequential art archive of excellence.",
    "The pull list is finally empty.",
    "A back-issue hunt that ended in glory.",
    "The superheroics of a true fan.",
    "A masterpiece of the ninth art.",
    "The comics are calling, I must go."
  ]
};

const GENERIC_EXPANSIONS = [
  "Logging another one for the vault.",
  "Adding to the collection.",
  "A fine addition to my collection.",
  "Lost in another world.",
  "The backlog grows ever larger.",
  "Will I ever finish everything?",
  "Time well spent.",
  "Another adventure logged.",
  "The lore deepens.",
  "So much to experience, so little time.",
  "A classic in the making.",
  "Another masterpiece consumed.",
  "Updating the master records.",
  "The vault expands.",
  "A journey of a thousand steps.",
  "The archive hungers.",
  "Preserved for eternity.",
  "A story worth remembering.",
  "The quintessential experience.",
  "Another notch on the belt.",
  "The legend continues.",
  "Found in the depths of the archive.",
  "A hidden gem of the collection.",
  "Tomes of forgotten knowledge.",
  "Whispers of past journeys.",
  "The definitive edition.",
  "A masterpiece in every sense.",
  "Witnessing greatness.",
  "Chronicles of the Lorekeeper.",
  "The shelf is getting heavy."
];

for (const type of Object.keys(MEDIA_FLAVOR_TEXTS)) {
  const currentTexts = MEDIA_FLAVOR_TEXTS[type];
  const thematicPool = THEMATIC_EXPANSIONS[type] || [];
  
  let fillerIndex = 0;
  while(currentTexts.length < 500) {
    if (fillerIndex < thematicPool.length) {
        currentTexts.push(thematicPool[fillerIndex]);
    } else {
        const genericText = GENERIC_EXPANSIONS[fillerIndex % GENERIC_EXPANSIONS.length];
        currentTexts.push(`${genericText}`);
    }
    fillerIndex++;
  }
}

export function getRandomFlavorText(mediaType: string): string {
  const texts = MEDIA_FLAVOR_TEXTS[mediaType] || ["Your entire history, collection, and backlog."];
  return texts[Math.floor(Math.random() * texts.length)];
}
