const fs = require('fs');

const extraFlavors = {
  "Game": [
    "Wololo.",
    "Do a kickflip!",
    "It's high noon.",
    "My body is ready.",
    "A Hideo Kojima Game.",
    "I'm here to kick ass and chew bubblegum.",
    "And I'm all out of bubblegum.",
    "The intent is to provide players with a sense of pride and accomplishment.",
    "Do you feel like a hero yet?",
    "Wake me when you need me.",
    "Praise Geraldo.",
    "We drop at Pochinki.",
    "Where we dropping, boys?",
    "I survived the Gulag and all I got was this log.",
    "Trust me.",
    "Protocol 3: Protect the Pilot.",
    "I gave the Covenant back their bomb.",
    "For a brick, he flew pretty good.",
    "You were almost a Jill sandwich!",
    "It's a-me, Mario!",
    "Let me guess, someone stole your sweetroll.",
    "Have you heard of the High Elves?",
    "STOP RIGHT THERE CRIMINAL SCUM!",
    "I don't need a weapon, my friends are my power!",
    "This is my story.",
    "Listen to my story. This may be our last chance.",
    "Nothing is true, everything is permitted.",
    "Requiescat in pace.",
    "It's not a bug, it's an undocumented feature.",
    "Lag.",
    "My ping is over 9000.",
    "360 no scope.",
    "Camping is a legitimate strategy.",
    "Reported for feeding.",
    "Mid or feed.",
    "Rush B.",
    "Cyka blyat.",
    "GGEZ.",
    "F in the chat.",
    "Press Alt+F4 for free loot.",
    "Any askers?",
    "L + ratio + you fell off.",
    "It really makes you feel like Spider-Man.",
    "10/10 has a little something for everyone.",
    "Too much water - IGN.",
    "Wow.",
    "Much game.",
    "Very graphics.",
    "Such gameplay.",
    "Do you guys not have phones?"
  ],
  "Book": [
    "So many books, so little time.",
    "I read it before it was a movie.",
    "I read it before it was a show.",
    "The book is literally a brick.",
    "Fantasy maps are my aesthetic.",
    "Why does every YA protagonist have silver hair?",
    "The Chosen One is tired.",
    "A Court of Thorns and Back Pain.",
    "Looking for my BookTok husband.",
    "I like big books and I cannot lie.",
    "Don't talk to me, I'm reading.",
    "Shhh, I'm at the good part.",
    "Enemies to lovers to enemies to lovers.",
    "There was only one bed.",
    "Who did this to you? (protective trope).",
    "Knife to the throat trope.",
    "Is this a kissing book?",
    "As you wish.",
    "To the stars who listen.",
    "And the dreams that are answered.",
    "I will have order!",
    "Words are wind.",
    "Winter is coming... eventually. Please George.",
    "Not my daughter, you b***",
    "After all this time? Always.",
    "You're a wizard, Harry.",
    "I am Lord Voldemort.",
    "Fear is the mind-killer.",
    "The spice must flow.",
    "I must not fear.",
    "Big Brother is watching you.",
    "War is peace. Freedom is slavery. Ignorance is strength.",
    "All animals are equal, but some animals are more equal than others.",
    "It was a pleasure to burn.",
    "Catch-22.",
    "Don't panic.",
    "Mostly harmless.",
    "42.",
    "So long, and thanks for all the fish.",
    "I meant what I said and I said what I meant.",
    "An elephant's faithful one hundred percent!",
    "Where the wild things are.",
    "Goodnight moon.",
    "Let the wild rumpus start!",
    "I solemnly swear that I am up to no good.",
    "Mischief managed.",
    "Stay gold, Ponyboy.",
    "Tomorrow is another day.",
    "Frankly my dear, I don't give a damn.",
    "I think I can, I think I can."
  ],
  "Audiobook": [
    "I'm not talking to myself, I'm listening to a book.",
    "My AirPods are glued to my ears.",
    "The narrator has a soothing voice.",
    "The narrator sounds like a robot.",
    "Did I miss a chapter or did the narrator skip?",
    "Playback speed: 1.25x is the sweet spot.",
    "Playback speed: 2.0x for maximum efficiency.",
    "Listening while staring off into space.",
    "I missed my highway exit because of a plot twist.",
    "If I pause it, I'll forget what happened.",
    "Earbuds in, world out.",
    "I'm absorbing literature via sound waves.",
    "Audible hopes you have enjoyed this program.",
    "This title is not available in your region.",
    "The sound effects are too loud.",
    "GraphicAudio: A movie in your mind.",
    "Full cast recordings are superior.",
    "Why does the male narrator do female voices like that?",
    "Why does the female narrator do male voices like that?",
    "When the author reads their own memoir.",
    "Celebrity narrators hit different.",
    "Listening to an audiobook about productivity while playing video games.",
    "It counts as reading!",
    "Yes, I read it. Well, I listened to it.",
    "I'm a visual learner, but an auditory reader.",
    "Falling asleep and waking up 5 chapters later.",
    "The sleep timer is my only friend.",
    "Who needs music when you have lore?",
    "Podcasts are nice, but audiobooks have a plot.",
    "I can't pause, I'm driving!",
    "Siri, rewind 30 seconds.",
    "Alexa, play my audiobook.",
    "Libby is my most used app.",
    "Waiting 12 weeks for a library hold.",
    "My TBR is just a huge audio playlist.",
    "Whispersync is magic.",
    "Syncing between Kindle and Audible is satisfying.",
    "Audiobooks make chores bearable.",
    "I look forward to commuting now.",
    "The gym is for audiobooks, not music.",
    "Narrator takes a breath... (I hear it).",
    "Can you repeat that? Oh wait, you're a recording.",
    "I have favorite narrators, not just favorite authors.",
    "Narrator pronounces the name wrong the entire book.",
    "I have no idea how any of these characters' names are spelled.",
    "Hermione? I thought it was Her-my-own.",
    "Listening at 0.75x speed makes everyone sound drunk.",
    "Listening at 3.0x speed sounds like a chipmunk.",
    "Audiobooks: because turning pages is too much work.",
    "The definitive way to consume massive fantasy tomes."
  ],
  "Visual Novel": [
    "This choice will have consequences.",
    "Will you remember this?",
    "Clementine will remember that.",
    "Objection! That statement contradicts the evidence!",
    "Take that!",
    "Hold it!",
    "The culprit is YOU!",
    "Updated the autopsy report.",
    "Almost stepped on a landmine there.",
    "Selecting the mean option to see what happens.",
    "Feeling guilty and reloading.",
    "I am thou, thou art I.",
    "Looking cool, Joker!",
    "For real?!",
    "A body has been discovered!",
    "Upupupu~",
    "It's punishment time!",
    "No, that's wrong!",
    "Allow me to cut through those words!",
    "Sore wa chigau yo!",
    "Hope vs. Despair.",
    "The ultimate lifeform.",
    "Just Monika.",
    "Okay, everyone!",
    "I gently open the door...",
    "Every day, I imagine a future where I can be with you.",
    "Steins;Gate is the choice of Steins Gate.",
    "El Psy Kongroo.",
    "I am mad scientist, it's so cool!",
    "Sonuvabitch.",
    "Tuturu~",
    "Fate/stay night: Unlimited Blade Works.",
    "People die if they are killed.",
    "The archer class really is made up of archers.",
    "Just because you're correct doesn't mean you're right.",
    "Trace on.",
    "Shirou, do you have enough swords in stock?",
    "When the seagulls cry.",
    "Without love, it cannot be seen.",
    "Ushiromiya Battler, I'm going to tear you apart!",
    "I refuse.",
    "Daga kotowaru.",
    "Clannad After Story destroyed me.",
    "Dango Daikazoku.",
    "Kanon is underrated.",
    "Air is a classic.",
    "Little Busters! are the best.",
    "Waku waku.",
    "Muv-Luv Alternative gave me PTSD.",
    "Katawa Shoujo is actually a masterpiece."
  ],
  "Manga": [
    "Omae wa mou shindeiru.",
    "NANI?!",
    "Yare yare daze.",
    "Kono Dio da!",
    "Za Warudo!",
    "Wryyyyyyy!",
    "Muda muda muda muda!",
    "Ora ora ora ora!",
    "Ho, you're approaching me?",
    "I can't beat the shit out of you without getting closer.",
    "Sokka.",
    "Equivalent exchange.",
    "Ed...ward...",
    "It's a terrible day for rain.",
    "What do you mean? It's not raining.",
    "I will take a potato chip... and eat it!",
    "All according to keikaku.",
    "(Translator's note: keikaku means plan)",
    "I am Goku, I'm insane! From earth!",
    "It's over 9000!",
    "Kakarot!",
    "Gomu Gomu no...",
    "The One Piece is real!",
    "I'm gonna be King of the Pirates!",
    "Nothing happened.",
    "Dattebayo!",
    "Believe it!",
    "I will become Hokage!",
    "Sasuke!",
    "Naruto!",
    "Bankai.",
    "Getsuga Tenshou!",
    "Domain Expansion.",
    "Nah, I'd win.",
    "Stand proud, you are strong.",
    "Are you the strongest because you're Satoru Gojo?",
    "With this treasure, I summon...",
    "Tatakae.",
    "If we kill all our enemies over there, will we finally be free?",
    "Give up your dreams and die.",
    "Erwin's charge.",
    "I am a hero for fun.",
    "Consecutive normal punches.",
    "100 pushups, 100 sit-ups, 100 squats, and a 10km run!",
    "Plus Ultra!",
    "Detroit Smash!",
    "I AM HERE!",
    "Eighty-Six. Glory to the Spearhead Squadron.",
    "Frieren goes on a journey.",
    "Aura, kill yourself."
  ],
  "Series": [
    "We were on a break!",
    "Pivot!",
    "Could I BE wearing any more clothes?",
    "How you doin'?",
    "Smelly cat, smelly cat...",
    "I'm not superstitious, but I am a little stitious.",
    "Bears. Beets. Battlestar Galactica.",
    "Identity theft is not a joke, Jim!",
    "That's what she said.",
    "I declare bankruptcy!",
    "Did I do that?",
    "Bazinga.",
    "I understood that reference.",
    "Title of your sex tape.",
    "Cool cool cool cool cool. No doubt no doubt no doubt.",
    "Nine-Nine!",
    "BONE?!",
    "Treat yo self.",
    "I know more than you.",
    "Parks and Rec > The Office.",
    "Winter is coming.",
    "The Lannisters send their regards.",
    "I drink and I know things.",
    "You know nothing, Jon Snow.",
    "Chaos is a ladder.",
    "I am the danger.",
    "I am the one who knocks.",
    "Say my name.",
    "Yeah, science!",
    "Better Call Saul!",
    "It's all good, man.",
    "Great Scott!",
    "Wubba lubba dub dub!",
    "I turned myself into a pickle, Morty!",
    "To be fair, you have to have a very high IQ to understand Rick and Morty.",
    "I am vengeance. I am the night. I am Batman!",
    "I'll be there for you.",
    "In the criminal justice system...",
    "Dun dun.",
    "The truth is out there.",
    "Trust no one.",
    "I want to believe.",
    "Live long and prosper.",
    "Resistance is futile.",
    "Make it so.",
    "Beam me up, Scotty.",
    "It's bigger on the inside.",
    "Wibbly wobbly, timey wimey.",
    "Exterminate!",
    "Delete!",
    "Allons-y!",
    "Geronimo!",
    "Bow ties are cool.",
    "Who killed Laura Palmer?",
    "The owls are not what they seem.",
    "Damn fine cup of coffee.",
    "We have to go back!",
    "Not Penny's boat.",
    "The numbers are bad."
  ],
  "Movie": [
    "I'll be back.",
    "Hasta la vista, baby.",
    "Get to the chopper!",
    "Come with me if you want to live.",
    "May the Force be with you.",
    "I am your father.",
    "Hello there.",
    "General Kenobi.",
    "I have the high ground.",
    "You underestimate my power.",
    "I don't like sand.",
    "It's a trap!",
    "Do, or do not. There is no try.",
    "I know.",
    "Here's looking at you, kid.",
    "We'll always have Paris.",
    "You're gonna need a bigger boat.",
    "I feel the need - the need for speed.",
    "To infinity and beyond!",
    "There's no place like home.",
    "I see dead people.",
    "Why so serious?",
    "Let's put a smile on that face.",
    "Some men just want to watch the world burn.",
    "You either die a hero, or you live long enough to see yourself become the villain.",
    "My precious.",
    "You shall not pass!",
    "One does not simply walk into Mordor.",
    "And my axe!",
    "Fly, you fools!",
    "I love the smell of napalm in the morning.",
    "Say hello to my little friend!",
    "You can't handle the truth!",
    "I'm going to make him an offer he can't refuse.",
    "Leave the gun, take the cannoli.",
    "You've got a friend in me.",
    "Hakuna Matata.",
    "Life finds a way.",
    "Clever girl.",
    "Welcome to Jurassic Park.",
    "We spared no expense.",
    "I am Iron Man.",
    "Avengers, assemble.",
    "I love you 3000.",
    "I don't feel so good.",
    "Perfectly balanced, as all things should be.",
    "First rule of Fight Club...",
    "The Matrix has you.",
    "There is no spoon.",
    "Red pill or blue pill?",
    "I know kung fu."
  ],
  "Comic": [
    "With great power comes great responsibility.",
    "I am Vengeance. I am the Night.",
    "Up, up, and away!",
    "Avengers Assemble!",
    "Flame on!",
    "It's clobberin' time!",
    "Hulk smash!",
    "Snikt!",
    "Thwip!",
    "Bamf!",
    "Excelsior!",
    "Make mine Marvel.",
    "In brightest day, in blackest night.",
    "Shazam!",
    "By the hoary hosts of Hoggoth!",
    "Imperius Rex!",
    "Hail Hydra.",
    "I can do this all day.",
    "On your left.",
    "Wakanda Forever.",
    "I am Groot.",
    "We are Groot.",
    "I'm the best there is at what I do.",
    "Sweet Christmas!",
    "My spider-sense is tingling.",
    "To me, my X-Men.",
    "Mutant and proud.",
    "Magneto was right.",
    "I am Fire and Life incarnate! Now and forever - I am PHOENIX!",
    "Face it Tiger, you just hit the jackpot.",
    "We live in a society.",
    "All it takes is one bad day.",
    "The joke's on you.",
    "I'm the goddamn Batman.",
    "Holy rusted metal, Batman!",
    "Some days you just can't get rid of a bomb.",
    "Kneel before Zod!",
    "I am the New God.",
    "Darkseid is.",
    "Anti-Life justifies my hate.",
    "Crisis on Infinite Earths.",
    "Secret Wars.",
    "Flashpoint.",
    "Who watches the Watchmen?",
    "Nothing ends, Adrian. Nothing ever ends.",
    "I'm not locked in here with you. You're locked in here with me!",
    "Remember, remember, the 5th of November.",
    "This city is afraid of me. I have seen its true face.",
    "I love independent comics.",
    "Image Comics > The Big Two."
  ]
};

let code = fs.readFileSync('src/lib/flavorTexts.ts', 'utf8');

for (const [type, lines] of Object.entries(extraFlavors)) {
  const searchString = `"${type}": [\n`;
  const insertIndex = code.indexOf(searchString);
  if (insertIndex !== -1) {
    const splitIndex = insertIndex + searchString.length;
    let insertion = '';
    for (const line of lines) {
      insertion += `    \`${line.replace(/`/g, '\\\\`')}\`,\n`;
    }
    code = code.slice(0, splitIndex) + insertion + code.slice(splitIndex);
  }
}

fs.writeFileSync('src/lib/flavorTexts.ts', code);
console.log("Added more flavor texts!");
