const fs = require('fs');

async function run() {
  const fileContent = fs.readFileSync('./src/lib/flavorTexts.ts', 'utf-8');
  let MEDIA_FLAVOR_TEXTS;
  
  // Quick extract logic since it's a TS file with an export
  try {
    const jsonStr = fileContent.match(/export const MEDIA_FLAVOR_TEXTS: Record<string, string\[\]> = (\{[\s\S]*?\});/)[1];
    MEDIA_FLAVOR_TEXTS = JSON.parse(jsonStr);
  } catch (e) {
    console.error("Failed to parse MEDIA_FLAVOR_TEXTS", e);
    return;
  }

  const NEW_TEXTS = {
    Game: [
      "Nothing is true, everything is permitted.", "I need a weapon.",
      "Stand in the ashes of a trillion dead souls and ask the ghosts if honor matters.",
      "Whether we wanted it or not, we've stepped into a war with the Cabal on Mars.",
      "You exist because we allow it, and you will end because we demand it.",
      "I am Andrew Ryan, and I'm here to ask you a question.", "Would you kindly?",
      "There is always a lighthouse, there's always a man, there's always a city.",
      "Bring us the girl and wipe away the debt.", "We are born of the blood, made men by the blood, undone by the blood.",
      "Fear the old blood.", "May you find your worth in the waking world.", "Hesitation is defeat.",
      "A shinobi would know the difference between honor and victory.", "Put these foolish ambitions to rest.",
      "Foul tarnished, in search of the Elden Ring.", "I vow to you, the Elden Ring will be forged anew.",
      "They played us like a damn fiddle!", "Snake, try to remember the basics of CQC.",
      "Kept you waiting, huh?", "War has changed.", "The flow of time is always cruel.",
      "You've met with a terrible fate, haven't you?", "Do you want to have a bad time?",
      "Despite everything, it's still you.", "It fills you with determination.", "Not even close, baby!",
      "ROCK AND STONE!", "If you don't rock and stone, you ain't comin' home.",
      "Look at them, they come to this place when they know they are not pure.",
      "What is a man? A miserable little pile of secrets!", "DIE, MONSTER! You don't belong in this world!",
      "But our princess is in another castle!", "A winner is you!", "All your base are belong to us.",
      "Do a barrel roll!", "Sir, Isaac Newton is the deadliest son-of-a-bitch in space!",
      "I'm Commander Shepard, and this is my favorite store on the Citadel.", "Endure and survive.",
      "Hey, you, you're finally awake.", "The numbers, Mason! What do they mean?!",
      "I'll have two number 9s...", "A man chooses, a slave obeys.", "Wake me... when you need me.",
      "Protocol 3: Protect the Pilot.", "Against all the evil that Hell can conjure...",
      "Rip and tear, until it is done.", "It's super effective!", "The factory must grow.",
      "Try fingers, but hole.", "Praise the message!", "Ah shit, here we go again.",
      "You have died of dysentery.", "It is dangerous to go alone! Take this.",
      "You must construct additional pylons.", "Job's done.", "Do you like hurting other people?"
    ],
    Book: [
      "It was a bright cold day in April, and the clocks were striking thirteen.",
      "It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of a wife.",
      "Call me Ishmael.", "The man in black fled across the desert, and the gunslinger followed.",
      "All children, except one, grow up.", "In a hole in the ground there lived a hobbit.",
      "Happy families are all alike; every unhappy family is unhappy in its own way.",
      "He loved Big Brother.", "I must not fear. Fear is the mind-killer.", "The spice must flow.",
      "It was the best of times, it was the worst of times.", "Stay gold, Ponyboy.",
      "We accept the love we think we deserve.", "So it goes.", "Reader, I married him.",
      "Don't panic.", "Forty-two.", "So long, and thanks for all the fish.", "I am Iron Gold.",
      "Hic est lupus, motherfucker.", "Omnis vir lupus.", "Break the chains.",
      "Violence is the last refuge of the incompetent.", "The building was on fire, and it wasn't my fault.",
      "Szeth-son-son-Vallano, Truthless of Shinovar, wore white on the day he was to kill a king.",
      "Life before death. Strength before weakness. Journey before destination.",
      "I will protect those who cannot protect themselves.", "No mating!", "I am a stick.",
      "Honor is dead, but I'll see what I can do.", "There's always another secret.",
      "Ash fell from the sky.", "The ships hung in the sky in much the same way that bricks don't.",
      "I solemnly swear that I am up to no good.", "Mischief managed.", "Yer a wizard, Harry.",
      "I volunteer as tribute!", "May the odds be ever in your favor.", "Look, I didn't want to be a half-blood.",
      "With great power... comes a great need to take a nap.", "As you wish.",
      "Hello. My name is Inigo Montoya. You killed my father. Prepare to die.",
      "Gatsby believed in the green light.",
      "And so we beat on, boats against the current, borne back ceaselessly into the past.",
      "I am haunted by humans.", "Things fall apart; the centre cannot hold.",
      "Water, water, every where, nor any drop to drink.",
      "Because I could not stop for Death, he kindly stopped for me.",
      "A mind needs books as a sword needs a whetstone.", "Words are our most inexhaustible source of magic.",
      "There is some good in this world, and it's worth fighting for.",
      "Whatever our souls are made of, his and mine are the same.", "Tomorrow is always fresh, with no mistakes in it yet.",
      "Fairy tales are more than true.", "I declare after all there is no enjoyment like reading!",
      "The scar had not pained Harry for nineteen years. All was well.", "Curiouser and curiouser!",
      "I am the Lorax. I speak for the trees."
    ],
    Audiobook: [
      "GraphicAudio: A Movie in Your Mind.", "This is Audible.", "We hope you have enjoyed this program.",
      "Audible hopes you have enjoyed this program.", "Narrated by Michael Kramer and Kate Reading.",
      "Narrated by Travis Baldree.", "Narrated by Simon Vance.", "Narrated by RC Bray.",
      "Narrated by Jim Dale.", "Narrated by Stephen Fry.", "Narrated by Ray Porter.",
      "Narrated by Tim Gerard Reynolds.", "Narrated by Nick Podehl.", "Narrated by Luke Daniels.",
      "Narrated by Jefferson Mays.", "Listening at 2.0x speed because the narrator is too slow.",
      "Whispersync for Voice is a lifesaver.", "I can't read physical books anymore, I can only listen.",
      "My commute is the only time I get to read.", "I sat in my driveway for 20 minutes to finish the chapter.",
      "Wait, what did he just say? Let me rewind 30 seconds.", "I fell asleep and missed 3 hours of the story.",
      "The narrator's voice for the female characters is... interesting.", "The accents are all over the place.",
      "Why did they add sound effects to this recording?", "The music transitions are way too loud.",
      "I love full cast audiobooks.", "I hate full cast audiobooks, just give me one good narrator.",
      "Dungeon Crawler Carl audio is better than the print version.",
      "Project Hail Mary on audio is an absolute masterpiece.", "Amaze! Amaze! Amaze!",
      "Glurp glurp.", "God dammit, Donut!", "Mongo is appalled!", "NEW ACHIEVEMENT!",
      "Listening to The Sandman audio drama.", "James McAvoy makes a great Morpheus.",
      "Podcast intro is 5 minutes long, skipping ahead.", "This episode is sponsored by Squarespace.",
      "Use promo code for 10% off.", "Welcome to Night Vale.", "Do not approach the Dog Park.",
      "And now, the weather.", "Statement begins.", "Statement ends.",
      "Ceaseless Watcher, turn your gaze upon this wretched thing.", "The Eye opens.",
      "A town called Lakeside.", "Earbuds locked in.", "The ultimate multitasking tool.",
      "Volume up, world down.", "This narrator has a ridiculous number of voices.",
      "The accompaniment PDF is missing."
    ],
    "Visual Novel": [
      "El Psy Kongroo.", "Tuturu~ Mayushii desu!", "I am mad scientist! It's so cool! Sonuvabitch!",
      "People die if they are killed.", "The archer class really is made up of archers!",
      "Just because you're correct doesn't mean you're right.", "Trace, on.", "I am the bone of my sword.",
      "Unlimited Blade Works.", "When the seagulls cry, none shall be left alive.",
      "Without love, it cannot be seen.", "Ushiromiya Battler, I'm going to tear you apart!",
      "Dango, dango, dango, dango, dango daikazoku.", "A body has been discovered!",
      "Upupupu~ It's punishment time!", "No, that's wrong!", "Sore wa chigau yo!",
      "Allow me to cut through those words!", "I'll cut through your words!", "I gently open the door...",
      "Just Monika.", "Every day, I imagine a future where I can be with you.",
      "This chair. This chair. This chair. This chair.", "Nanaya grindset.", "Defenseless.",
      "KIMI TO ISSHO GA ICHIBAN.", "Shirou, do you have enough swords in stock?",
      "Rejoice, boy. Your wish will finally come true.", "I'll destroy that screwed up illusion of yours!",
      "Nipah~", "Wakarimasu.", "Truth is subjective.", "It's a trick, magic isn't real.",
      "Blue truth. Red truth. Gold truth.", "CHOMP.", "Please read the VN.",
      "The anime adaptation was a mistake.", "Save scumming to avoid the bad end.",
      "Following a walkthrough step by step.", "I don't have time to unlock all the CGs, give me the 100% save file.",
      "Jun Maeda magic.", "Kinoko Nasu's mushroomverse.", "Ryukishi07's derp faces and big hands.",
      "Uchikoshi's mind-bending twists.", "My motives are complex.", "Life is simply unfair, don't you think?",
      "What the hell is a Funyarinpa?", "I am Zero.", "Seek a way out!", "Hope vs Despair.",
      "Nagito Komaeda's luck cycle.", "Kokichi Oma's lies.", "OBJECTION!", "HOLD IT!", "TAKE THAT!",
      "Updated autopsy report.", "The miracle never happen.", "Kurisu is a tsundere.",
      "Mayuri's pocket watch stopped...", "Ushio...", "There is no Tsukihime anime in Ba Sing Se.",
      "Meat vision.", "Down the rabbit hole.", "Live, live, live!", "Juicy Yuuji.",
      "Hisao's heart go thump.", "Emi's lemons.", "Hanako's bacon.", "Lilly's tea.", "Rin's armless art.",
      "Shizune's chess.", "Kenji's feminist conspiracy theories.", "Press space/enter to advance text.",
      "Skip previously read text.", "Playing purely for the plot. Sure you are.",
      "A bad end is just a stepping stone.", "Clear file unlocked.", "Eternum server is online.",
      "Trust the process.", "Leap of faith.", "Rendered in Ren'Py engine.",
      "Almost Christmas means it wasn't Christmas!", "Cross-examining a parrot.",
      "Von Karma's penalty.", "Gumshoe's salary cut.", "Pursuit - Cornered plays.",
      "Did you know that Bungee Gum possesses the properties of both rubber and gum? Wait, wrong medium.",
      "Kamukura, Kamukura, yass queen!", "Meat on the bone! On the meat bone! Bone the meat on!",
      "Makoto Naegi's ahoge provides hope.", "Hajime's orange juice.", "Time to mix drinks and change lives.",
      "Every day is great at your Junes!", "A snail. Complex motives. Phi's jumps.",
      "Grab my hand, River.", "The narrator is lying to you.", "You are on a path in the woods.",
      "I'm not a furry, but...", "The true route is always locked at the start.",
      "100% CG completion.", "Only 50 more hours to the true ending.", "A 100-hour visual novel."
    ],
    Movie: [
      "I am your father.", "May the Force be with you.", "I'll be back.", "You're gonna need a bigger boat.",
      "The first rule of Fight Club is: You do not talk about Fight Club.", "There's no place like home.",
      "Life was like a box of chocolates. You never know what you're gonna get.", "Here's looking at you, kid.",
      "E.T. phone home.", "To infinity and beyond!", "I'm the king of the world!", "Houston, we have a problem.",
      "There's no crying in baseball!", "You can't handle the truth!", "I see dead people.", "My precious.",
      "Why so serious?", "I am Iron Man.", "Avengers, assemble.", "Say 'hello' to my little friend!",
      "I'm gonna make him an offer he can't refuse.", "Frankly, my dear, I don't give a damn.",
      "Toto, I've a feeling we're not in Kansas anymore.", "Show me the money!", "You talkin' to me?",
      "Roads? Where we're going, we don't need roads.", "Keep your friends close, but your enemies closer.",
      "Do, or do not. There is no try.", "Welcome to Jurassic Park.", "I am serious... and don't call me Shirley.",
      "As far back as I can remember, I always wanted to be a gangster.", "Choose life.",
      "I'll have what she's having.", "Hasta la vista, baby.", "Yippee-ki-yay, motherf*cker.",
      "I feel the need—the need for speed.", "I am Groot.", "Wakanda Forever.", "I can do this all day.",
      "We're in the endgame now.", "I love you 3000.", "That's my secret, Cap. I'm always angry.",
      "I am inevitable.", "I'm Batman.", "Some men just want to watch the world burn.",
      "The things you own end up owning you.",
      "I don't know who you are. I don't know what you want... but I will find you, and I will kill you.",
      "I drink your milkshake! I drink it up!", "Get busy living, or get busy dying.",
      "I've seen things you people wouldn't believe.", "All those moments will be lost in time, like tears in rain.",
      "Hello there.", "General Kenobi!", "It's over, Anakin! I have the high ground!",
      "I don't like sand. It's coarse and rough and irritating and it gets everywhere.",
      "This is where the fun begins.", "A surprise to be sure, but a welcome one.", "I am the Senate.",
      "Inconceivable!", "It's not a loop, it's a spiral.", "BWAHHH (Inception horn).",
      "We live in a twilight world. And there are no friends at dusk.", "It's Morbin' time.",
      "I am McLovin.", "You sit on a throne of lies.", "What's in the box?!",
      "You met me at a very strange time in my life.", "Just keep swimming.", "I am the captain now.",
      "Look at me.", "Are you not entertained?!", "What we do in life echoes in eternity.",
      "They may take our lives, but they'll never take our freedom!", "I abandoned my child!",
      "I'm mad as hell, and I'm not going to take this anymore!", "You're tearing me apart, Lisa!",
      "Oh, hi Mark.", "The room is a masterpiece.", "Spoon!", "A boy's best friend is his mother.",
      "They're here.", "A census taker once tried to test me. I ate his liver with some fava beans and a nice Chianti.",
      "It puts the lotion on its skin.", "Here's Johnny!", "Redrum. REDRUM.",
      "All work and no play makes Jack a dull boy.",
      "You either die a hero, or you live long enough to see yourself become the villain.",
      "It's not who I am underneath, but what I do that defines me.", "Swear to me!",
      "Where is the trigger?!", "I am Vengeance.", "I'm Mary Poppins, y'all!",
      "I have been falling... for thirty minutes!", "Shrek is love, Shrek is life.",
      "Get out of my swamp!", "Ogres are like onions.", "Donkeys!", "Do the roar.",
      "That'll do, Donkey. That'll do.", "I'm a real boy!", "Hakuna Matata.", "Long live the king.",
      "Remember who you are.", "You are a sad, strange little man.", "There's a snake in my boot!", "Reach for the sky!"
    ],
    Series: [],
    Manga: [
      "I am the hope of the universe.", "Omae wa mou shindeiru.", "NANI?!",
      "I will take a potato chip... and eat it!", "Equivalent exchange.", "Bankai.",
      "Domain Expansion: Infinite Void.", "Domain Expansion: Malevolent Shrine.",
      "I'm gonna be King of the Pirates!", "Stand proud, you are strong.", "Nah, I'd win.",
      "It was me, Dio!", "I reject my humanity, JoJo!", "Yare yare daze.",
      "What a beautiful Duwang.", "People's dreams... HAVE NO END!", "The One Piece is real!",
      "This world is rotten.", "All according to keikaku. (Translator's note: keikaku means plan)",
      "Can we get much higher?", "I want to live!", "Nothing happened.", "Dattebayo!",
      "Give up on your dreams and die.", "Tatakae. Tatakae.",
      "I keep moving forward, until my enemies are destroyed.",
      "Since when were you under the impression that I wasn't using Kyoka Suigetsu?",
      "You spin me right round, baby, right round.", "He laughed.", "GOMU GOMU NO...",
      "Gear Second.", "Gear Fourth.", "Gear Fifth.", "Kaizoku ou ni ore wa naru!",
      "I'm gonna be Hokage!", "Believe it!", "Rasengan!", "Chidori!",
      "Talk no Jutsu is the strongest technique.", "I will save you, Sasuke!", "Getsuga Tensho!",
      "I am a Quincy.", "Hollowfication.", "Kamehameha!", "It's over 9000!",
      "Super Saiyan.", "Ultra Instinct.", "Frieza!", "Plus Ultra!", "Detroit Smash!",
      "One For All.", "Half-cold, half-hot.", "It's fine now. Why? Because I am here!",
      "Ed...ward...", "It's a terrible day for rain.", "Justaway.",
      "Neo Armstrong Cyclone Jet Armstrong Cannon.", "Tetsuo!", "Kaneda!", "Ora ora ora!",
      "Muda muda muda!", "Za Warudo! Toki yo tomare!", "King Crimson just works.",
      "I, Giorno Giovanna, have a dream.", "Arigato, Gyro.",
      "Pizza Mozzarella, Pizza Mozzarella, Rella Rella Rella.", "Hiatus x Hiatus.", "Gon's hair.",
      "Bungee Gum possesses the properties of both rubber and gum.", "Meruem.",
      "Komugi, are you still there?", "Shinigami love apples.", "I am L.", "I am Kira.",
      "Shinzou wo Sasageyo!", "Levi's beyblade.", "Eren did nothing wrong.",
      "Rumbling, rumbling, it's coming!", "Tenoi.", "Enough time has passed. (Kagurabachi)",
      "Peak fiction.", "Read the manga.", "The anime is catching up, filler arc incoming.",
      "Waiting for the scanlations.", "The raw chapters are out.", "Weekly Shonen Jump.",
      "Mangaka needs a break, hiatus.", "Axe'd after 15 chapters.", "It peaked in the Golden Age arc.",
      "You are my special.",
      "Are you the strongest because you're Satoru Gojo? Or are you Satoru Gojo because you're the strongest?",
      "Throughout Heaven and Earth, I alone am the honored one.", "Griffith did nothing wrong.",
      "Struggle, Contend, Survive.", "Don't put your grasses on, nothing will be wong.",
      "You have no enemies.", "A true warrior needs no sword.",
      "Look at me, the monster inside me has grown this large.",
      "Dear God, tinkle tinkle hoy.", "What's 1000 minus 7?",
      "Oshiete, oshiete yo sono shikumi wo...", "I love the kind of woman that can kick my ass.",
      "Bark for Makima.", "Aki's snowball fight.", "Power's Nobel Prize.", "Become Fire Punch.",
      "Aura, kill yourself.", "It's been 80 years since the hero Himmel's death.",
      "Magic that creates fields of flowers.", "Zoltraak.", "Waku waku!", "Anya's smug face.",
      "Elegant!", "Water Breathing, First Form.", "Set your heart ablaze.",
      "Tadano is an absolute chad.", "O kawaii koto.", "Baking soda genius child actor.",
      "Invincible under the sun.", "I'm a genius! (Sakuragi)", "The left hand is just for support.",
      "Rolling Thunder!", "The Generation of Miracles.", "I am a striker. Devour them.",
      "Dempsey Roll!", "Body Improvement Club! Fight on!",
      "100 push-ups, 100 sit-ups, 100 squats, and a 10km run EVERY DAY!", "Ok. (Saitama)",
      "The legendary double-page spread.", "Kagome!", "SIT, boy!", "In the name of the moon, I'll punish you!",
      "Kiss kiss fall in love.", "Damn rich people.", "This hole was made for me.",
      "Get in the robot, Shinji.", "I mustn't run away.", "Congratulations!",
      "You can (not) redo.", "See you space cowboy.", "Whatever happens, happens.",
      "Love and peace!", "Bitches love cannons.", "A true warrior needs no sword."
    ],
    Comic: [
      "With great power comes great responsibility.", "I am Batman.", "Avengers assemble!",
      "Up, up and away!", "It's clobberin' time!", "Snikt!", "In brightest day, in blackest night.",
      "HULK SMASH!", "Imperius Rex!", "I'm the best there is at what I do, but what I do best isn't very nice.",
      "To me, my X-Men.", "Who watches the Watchmen?", "I'm not locked in here with you. You're locked in here with me.",
      "We live in a society.", "Because I'm Batman!", "Flame on!", "Shazam!", "BAMF!", "THWIP!",
      "Excelsior!", "Make mine Marvel.", "Welcome to the X-Men, hope you survive the experience.",
      "I am Vengeance. I am the Night.", "Some days, you just can't get rid of a bomb.",
      "Holy bat-tropes, Batman!", "All it takes is one bad day to reduce the sanest man alive to lunacy.",
      "It was me, Barry!", "My name is Barry Allen, and I am the fastest man alive.",
      "Truth, Justice, and the American Way.", "Kneel before Zod!", "Look, up in the sky! It's a bird, it's a plane!",
      "Lex Luthor stole forty cakes. That's as many as four tens. And that's terrible.",
      "Aquaman talks to fish.", "Outrageous!", "Beware my power, Green Lantern's light!",
      "Chimichangas!", "Maximum Effort.", "My spider-sense is tingling.", "Typical Parker Luck.",
      "Face it, tiger... you just hit the jackpot!", "SNAP.", "Magneto was right.",
      "Cyclops was right.", "Professor X is a jerk.", "Fastball special.", "I am Groot.",
      "I am Steve Rogers.", "Hail Hydra.", "Wakanda Forever.", "Richards! Doom demands your attention.",
      "Doom is supreme. Kneel before Doom.", "There is no God. Only Doom.",
      "I can do this all day.", "That's America's ass.", "Nothing stops the Juggernaut!",
      "Sweet Christmas!", "I'm the goddamn Batman.", "Wait'll they get a load of me.",
      "You don't get it, boy... this isn't a mudhole... It's an operating table.",
      "Good evening, Commissioner.", "Why did you say that name?!", "A glass of water, please.",
      "Don't make me angry. You wouldn't like me when I'm angry.",
      "I am the law!", "Gaze into the fist of Dredd!", "Drokk!",
      "Cowabunga!", "Turtle Power!", "A god walks into Abar, and he orders a beer.",
      "Nothing ever ends.", "I did it thirty-five minutes ago.",
      "We're the authority... and we're here to save you.", "This is the story of how I died.",
      "I am Ozymandias, King of Kings.", "There's a starman waiting in the sky.",
      "The world is a vampire.", "Remember, remember, the fifth of November.",
      "Ideas are bulletproof.", "England prevails.",
      "People shouldn't be afraid of their government. Governments should be afraid of their people.",
      "I love the smell of napalm in the morning.", "Rorschach's Journal. October 12th, 1985.",
      "Never compromise. Not even in the face of Armageddon.", "I leave the world in your hands, Clark.",
      "A Superman for all seasons.", "I am a man of my word.", "Bop! Pow! Bam!",
      "Great krypton!", "By the hoary hosts of Hoggoth!", "By the Crimson Bands of Cyttorak!",
      "Eye of Agamotto.", "Dormammu, I've come to bargain.", "I can do whatever the f*ck I want.",
      "Diabolical.", "Scorched earth.", "Eat my shorts.", "Getafix's magic potion.",
      "By Toutatis!", "These Romans are crazy.", "Right Hand of Doom.", "I hate Nazis.",
      "Transmogrifier box.", "Calvinball rules.", "Spaceman Spiff.", "Good grief.",
      "It's the Great Pumpkin!", "Snoopy vs the Red Baron.", "Garfield hates Mondays.",
      "I'm sorry, Jon.", "Maus: A Survivor's Tale.", "I want to be a Jedi.",
      "Doomsday is coming.", "The Robin curse.", "Lazarus Pit.", "Omega beams.",
      "The Anti-Life Equation.", "Darkseid is."
    ]
  };

  for (const category in MEDIA_FLAVOR_TEXTS) {
    if (NEW_TEXTS[category]) {
      const existing = MEDIA_FLAVOR_TEXTS[category];
      const combined = [...existing, ...NEW_TEXTS[category]];
      const unique = Array.from(new Set(combined));
      MEDIA_FLAVOR_TEXTS[category] = unique;
    }
  }

  const exportString = `export const MEDIA_FLAVOR_TEXTS: Record<string, string[]> = ${JSON.stringify(MEDIA_FLAVOR_TEXTS, null, 2)};\n` +
  `\nexport function getRandomFlavorText(type: string): string {\n  if (!type || !MEDIA_FLAVOR_TEXTS[type] || MEDIA_FLAVOR_TEXTS[type].length === 0) {\n    return 'A classic masterpiece.';\n  }\n  const texts = MEDIA_FLAVOR_TEXTS[type];\n  return texts[Math.floor(Math.random() * texts.length)];\n}\n`;
  
  fs.writeFileSync('./src/lib/flavorTexts.ts', exportString);
  console.log("Updated flavorTexts.ts!");
}

run();
