import fs from 'fs';

const GAMING_QUOTES = [
  { quote: "Juffo-Wup fills in my omissions.", source: "Star Control II" },
  { quote: "Launch fighters!", source: "Star Control II" },
  { quote: "We come in peace. We are the Ur-Quan.", source: "Star Control II" },
  { quote: "Did you see my flag?", source: "Plok" },
  { quote: "Fleas everywhere!", source: "Plok" },
  { quote: "Tim Follin's masterpiece soundtrack.", source: "Plok" },
  { quote: "Those who rely on the power of another...", source: "Live A Live" },
  { quote: "Megalomania.", source: "Live A Live" },
  { quote: "Oersted did nothing wrong.", source: "Live A Live" },
  { quote: "Resurrect the world.", source: "Terranigma" },
  { quote: "A small bird brought a message.", source: "Terranigma" },
  { quote: "That ending though...", source: "Terranigma" },
  { quote: "Blood geysers.", source: "Vandal Hearts" },
  { quote: "Vandalier class.", source: "Vandal Hearts" },
  { quote: "A tactical RPG pioneer.", source: "Vandal Hearts" },
  { quote: "Beans, beans, the musical fruit.", source: "Skullmonkeys" },
  { quote: "Willie Trombone!", source: "Skullmonkeys" },
  { quote: "A true claymation fever dream.", source: "Skullmonkeys" },
  { quote: "Minku!", source: "Brave Fencer Musashi" },
  { quote: "Lumina, sword of luminescence!", source: "Brave Fencer Musashi" },
  { quote: "Sleep deprivation mechanics.", source: "Brave Fencer Musashi" },
  { quote: "Ulukai.", source: "Outcast" },
  { quote: "Greetings, Cutter Slade.", source: "Outcast" },
  { quote: "Voxel landscapes ahead of their time.", source: "Outcast" },
  { quote: "Transfer your soul.", source: "Omikron: The Nomad Soul" },
  { quote: "David Bowie is everywhere.", source: "Omikron: The Nomad Soul" },
  { quote: "The Dreamers.", source: "Omikron: The Nomad Soul" },
  { quote: "The blood is the life.", source: "Vagrant Story" },
  { quote: "Reinforcements? I am the reinforcements.", source: "Vagrant Story" },
  { quote: "Ashley Riot's fabulous chaps.", source: "Vagrant Story" },
  { quote: "Moons give me strength!", source: "Skies of Arcadia" },
  { quote: "Vyse the Legend.", source: "Skies of Arcadia" },
  { quote: "Random encounters every two steps.", source: "Skies of Arcadia" },
  { quote: "Kabuto smash!", source: "Giants: Citizen Kabuto" },
  { quote: "Meccaryns.", source: "Giants: Citizen Kabuto" },
  { quote: "Base building in a shooter?", source: "Giants: Citizen Kabuto" },
  { quote: "Volcano!", source: "The Legend of Dragoon" },
  { quote: "Gust of Wind Dance!", source: "The Legend of Dragoon" },
  { quote: "Lavitz... :(", source: "The Legend of Dragoon" },
  { quote: "Sly Boots.", source: "Anachronox" },
  { quote: "Fatty Fargo.", source: "Anachronox" },
  { quote: "Having a literal planet in your party.", source: "Anachronox" },
  { quote: "The horror park.", source: "Illbleed" },
  { quote: "Eriko!", source: "Illbleed" },
  { quote: "Checking every room for traps.", source: "Illbleed" },
  { quote: "Judgment Ring.", source: "Shadow Hearts" },
  { quote: "Malice.", source: "Shadow Hearts" },
  { quote: "Yuri Hyuga's transformations.", source: "Shadow Hearts" },
  { quote: "Show me your wares.", source: "Gothic II" },
  { quote: "For Innos!", source: "Gothic II" },
  { quote: "Getting killed by a meatbug.", source: "Gothic II" },
  { quote: "For the rebellion!", source: "Freedom Fighters" },
  { quote: "Plumber.", source: "Freedom Fighters" },
  { quote: "Jesper Kyd's choir soundtrack.", source: "Freedom Fighters" },
  { quote: "Propaganda!", source: "Beyond Good & Evil" },
  { quote: "Carlson & Peeters.", source: "Beyond Good & Evil" },
  { quote: "Still waiting for the sequel...", source: "Beyond Good & Evil" },
  { quote: "Mummy platforming.", source: "Sphinx and the Cursed Mummy" },
  { quote: "Blade of Osiris.", source: "Sphinx and the Cursed Mummy" },
  { quote: "The infamous save-corrupting bug.", source: "Sphinx and the Cursed Mummy" },
  { quote: "Derrick Cole.", source: "Breakdown" },
  { quote: "First-person eating.", source: "Breakdown" },
  { quote: "First-person backflips.", source: "Breakdown" },
  { quote: "The dark... are you afraid of the dark?", source: "The Chronicles of Riddick: Escape from Butcher Bay" },
  { quote: "Get him a surgeon.", source: "The Chronicles of Riddick: Escape from Butcher Bay" },
  { quote: "Shank combat simulator.", source: "The Chronicles of Riddick: Escape from Butcher Bay" },
  { quote: "I am the milkman. My milk is delicious.", source: "Psychonauts" },
  { quote: "Lungfishopolis.", source: "Psychonauts" },
  { quote: "The Meat Circus.", source: "Psychonauts" },
  { quote: "In the name of Harman.", source: "Killer7" },
  { quote: "Heaven Smile.", source: "Killer7" },
  { quote: "Master, we're in a tight spot!", source: "Killer7" },
  { quote: "Brains!", source: "Stubbs the Zombie" },
  { quote: "Maggie Monday.", source: "Stubbs the Zombie" },
  { quote: "Bowling with your own head.", source: "Stubbs the Zombie" },
  { quote: "Rau and Kuzo.", source: "The Mark of Kri" },
  { quote: "Stealth kills.", source: "The Mark of Kri" },
  { quote: "Right stick combat system.", source: "The Mark of Kri" },
  { quote: "May God have mercy on your soul.", source: "Call of Juarez" },
  { quote: "Reverend Ray.", source: "Call of Juarez" },
  { quote: "Reading the Bible while shooting outlaws.", source: "Call of Juarez" },
  { quote: "Kyle Hyde.", source: "Hotel Dusk: Room 215" },
  { quote: "Red Crown.", source: "Hotel Dusk: Room 215" },
  { quote: "Holding your DS sideways.", source: "Hotel Dusk: Room 215" },
  { quote: "For France!", source: "Jeanne d'Arc" },
  { quote: "Armlet power.", source: "Jeanne d'Arc" },
  { quote: "Historical inaccuracy with frogs.", source: "Jeanne d'Arc" },
  { quote: "Zetta slow!", source: "The World Ends with You" },
  { quote: "Calling!", source: "The World Ends with You" },
  { quote: "So zetta slow!", source: "The World Ends with You" },
  { quote: "A Thousand Years of Dreams.", source: "Lost Odyssey" },
  { quote: "Kaim Argonar.", source: "Lost Odyssey" },
  { quote: "The true Final Fantasy XIII.", source: "Lost Odyssey" },
  { quote: "Faith.", source: "Mirror's Edge" },
  { quote: "Runner vision.", source: "Mirror's Edge" },
  { quote: "Still Alive.", source: "Mirror's Edge" },
  { quote: "Isn't that right, Zach?", source: "Deadly Premonition" },
  { quote: "F K... in the coffee.", source: "Deadly Premonition" },
  { quote: "The Sinner's Sandwich.", source: "Deadly Premonition" },
  { quote: "Monkey and Trip.", source: "Enslaved: Odyssey to the West" },
  { quote: "Pigsy.", source: "Enslaved: Odyssey to the West" },
  { quote: "Andy Serkis as a cloud-riding monkey.", source: "Enslaved: Odyssey to the West" },
  { quote: "Time Manipulation Device.", source: "Singularity" },
  { quote: "Barisov.", source: "Singularity" },
  { quote: "Reverting soldiers into dust.", source: "Singularity" },
  { quote: "A Steven Heck of a time.", source: "Alpha Protocol" },
  { quote: "Orphans.", source: "Alpha Protocol" },
  { quote: "The dialogue timer is running out!", source: "Alpha Protocol" },
  { quote: "Sean Devlin.", source: "The Saboteur" },
  { quote: "Color returns.", source: "The Saboteur" },
  { quote: "Blowing up zeppelins in black and white Paris.", source: "The Saboteur" },
  { quote: "Sissel.", source: "Ghost Trick: Phantom Detective" },
  { quote: "Missile!", source: "Ghost Trick: Phantom Detective" },
  { quote: "4 minutes before death.", source: "Ghost Trick: Phantom Detective" },
  { quote: "Are you sure that's enough armor?", source: "El Shaddai: Ascension of the Metatron" },
  { quote: "No, I want the best.", source: "El Shaddai: Ascension of the Metatron" },
  { quote: "Denim jeans in heaven.", source: "El Shaddai: Ascension of the Metatron" },
  { quote: "Big Bo.", source: "Binary Domain" },
  { quote: "Scrapheads.", source: "Binary Domain" },
  { quote: "Yelling commands at your TV.", source: "Binary Domain" },
  { quote: "Do you feel like a hero yet?", source: "Spec Ops: The Line" },
  { quote: "White phosphorus.", source: "Spec Ops: The Line" },
  { quote: "Welcome to Dubai.", source: "Spec Ops: The Line" },
  { quote: "A man who never eats pork buns is never a whole man!", source: "Sleeping Dogs" },
  { quote: "Wei Shen.", source: "Sleeping Dogs" },
  { quote: "Environmental takedowns in the night market.", source: "Sleeping Dogs" },
  { quote: "Burst!", source: "Asura's Wrath" },
  { quote: "Six-Armed Vajra Asura.", source: "Asura's Wrath" },
  { quote: "Punching the finger of a god.", source: "Asura's Wrath" },
  { quote: "Memory remix.", source: "Remember Me" },
  { quote: "Nilin.", source: "Remember Me" },
  { quote: "Neo-Paris 2084.", source: "Remember Me" },
  { quote: "Kutaro.", source: "Puppeteer" },
  { quote: "Moon Bear King.", source: "Puppeteer" },
  { quote: "Theatre stage platforming.", source: "Puppeteer" },
  { quote: "Glass him.", source: "The Wolf Among Us" },
  { quote: "Bigby.", source: "The Wolf Among Us" },
  { quote: "Fabletown will remember that.", source: "The Wolf Among Us" },
  { quote: "Emile.", source: "Valiant Hearts: The Great War" },
  { quote: "Walt.", source: "Valiant Hearts: The Great War" },
  { quote: "The saddest dog simulator.", source: "Valiant Hearts: The Great War" },
  { quote: "Awesomepocalypse.", source: "Sunset Overdrive" },
  { quote: "Overcharge.", source: "Sunset Overdrive" },
  { quote: "Grinding on wires with a teddy bear launcher.", source: "Sunset Overdrive" },
  { quote: "Simon, are you there?", source: "SOMA" },
  { quote: "Coin flip.", source: "SOMA" },
  { quote: "Existential dread at the bottom of the ocean.", source: "SOMA" },
  { quote: "Hannah.", source: "Her Story" },
  { quote: "Eve.", source: "Her Story" },
  { quote: "Typing 'murder' into a retro database.", source: "Her Story" },
  { quote: "Witness me!", source: "Mad Max" },
  { quote: "Chumbucket.", source: "Mad Max" },
  { quote: "The Magnum Opus.", source: "Mad Max" },
  { quote: "Broadside combat.", source: "Rebel Galaxy" },
  { quote: "Space truckers.", source: "Rebel Galaxy" },
  { quote: "Blues-rock in the void of space.", source: "Rebel Galaxy" },
  { quote: "The Jailer is the key.", source: "Furi" },
  { quote: "A flawless parry.", source: "Furi" },
  { quote: "Synthwave boss rush.", source: "Furi" },
  { quote: "Fatebinder.", source: "Tyranny" },
  { quote: "Kyros.", source: "Tyranny" },
  { quote: "Sometimes, evil has already won.", source: "Tyranny" },
  { quote: "Time is power.", source: "Quantum Break" },
  { quote: "Jack Joyce.", source: "Quantum Break" },
  { quote: "Wait, is this a TV show or a game?", source: "Quantum Break" },
  { quote: "Leave. Possible.", source: "Oxenfree" },
  { quote: "Sunken.", source: "Oxenfree" },
  { quote: "Tuning the radio to ghost frequencies.", source: "Oxenfree" },
  { quote: "Not a Mimic.", source: "Prey" },
  { quote: "Morgan Yu.", source: "Prey" },
  { quote: "Why is that coffee cup shaking?", source: "Prey" },
  { quote: "What remains.", source: "What Remains of Edith Finch" },
  { quote: "Gregory's bath.", source: "What Remains of Edith Finch" },
  { quote: "The fish factory daydream.", source: "What Remains of Edith Finch" },
  { quote: "Groundhog day murder.", source: "The Sexy Brutale" },
  { quote: "Marquis.", source: "The Sexy Brutale" },
  { quote: "Rewinding the clock.", source: "The Sexy Brutale" },
  { quote: "Lea!", source: "CrossCode" },
  { quote: "Hi!", source: "CrossCode" },
  { quote: "The ball physics puzzles...", source: "CrossCode" },
  { quote: "This is my blood.", source: "Vampyr" },
  { quote: "Jonathan Reid.", source: "Vampyr" },
  { quote: "To embrace or not to embrace.", source: "Vampyr" },
  { quote: "Captain Robert Witterel.", source: "Return of the Obra Dinn" },
  { quote: "Fate of the crew.", source: "Return of the Obra Dinn" },
  { quote: "Crushed by a loose cannon.", source: "Return of the Obra Dinn" },
  { quote: "Grandpa Nonno.", source: "Mutazione" },
  { quote: "Gardening.", source: "Mutazione" },
  { quote: "Musical gardens.", source: "Mutazione" },
  { quote: "Squisherz.", source: "Hypnospace Outlaw" },
  { quote: "Granny Hazel.", source: "Hypnospace Outlaw" },
  { quote: "Enforcing laws on the late 90s internet.", source: "Hypnospace Outlaw" },
  { quote: "There's more to explore here.", source: "Outer Wilds" },
  { quote: "End of the universe.", source: "Outer Wilds" },
  { quote: "22 minutes until the sun explodes.", source: "Outer Wilds" },
  { quote: "Lady Love Dies.", source: "Paradise Killer" },
  { quote: "Blood Drop.", source: "Paradise Killer" },
  { quote: "City Pop vaporwave murder mystery.", source: "Paradise Killer" },
  { quote: "Too fast, too soon.", source: "Inscryption" },
  { quote: "Stoat.", source: "Inscryption" },
  { quote: "Sacrifice your friends for power.", source: "Inscryption" },
  { quote: "The Golden Rule.", source: "The Forgotten City" },
  { quote: "Many shall suffer for the sins of the one.", source: "The Forgotten City" },
  { quote: "Groundhog day in ancient Rome.", source: "The Forgotten City" },
  { quote: "Where does this go?", source: "Unpacking" },
  { quote: "Pig plushie.", source: "Unpacking" },
  { quote: "Storytelling through objects.", source: "Unpacking" },
  { quote: "A Colorful Tale.", source: "Chicory: A Colorful Tale" },
  { quote: "Brush wielding.", source: "Chicory: A Colorful Tale" },
  { quote: "Coloring outside the lines.", source: "Chicory: A Colorful Tale" },
  { quote: "CEO mindset.", source: "Cruelty Squad" },
  { quote: "Flesh automaton.", source: "Cruelty Squad" },
  { quote: "Investing in slurp juices.", source: "Cruelty Squad" },
  { quote: "Wake up, sleeper.", source: "Citizen Sleeper" },
  { quote: "Cycles.", source: "Citizen Sleeper" },
  { quote: "Rolling dice to survive capitalism.", source: "Citizen Sleeper" },
  { quote: "Remember our promise.", source: "Signalis" },
  { quote: "LSTR.", source: "Signalis" },
  { quote: "Six up, six down inventory.", source: "Signalis" },
  { quote: "Andreas Maler.", source: "Pentiment" },
  { quote: "Tassing.", source: "Pentiment" },
  { quote: "A medieval tapestry come to life.", source: "Pentiment" },
  { quote: "Marissa Marcel.", source: "Immortality" },
  { quote: "Moviola.", source: "Immortality" },
  { quote: "Hidden frames.", source: "Immortality" },
  { quote: "Louisiana swamp.", source: "Norco" },
  { quote: "Million.", source: "Norco" },
  { quote: "Southern Gothic point-and-click.", source: "Norco" },
  { quote: "Fox with a sword.", source: "Tunic" },
  { quote: "Holy Cross.", source: "Tunic" },
  { quote: "Golden Path.", source: "Tunic" },
  { quote: "Sky Armor.", source: "Chained Echoes" },
  { quote: "Glenn.", source: "Chained Echoes" },
  { quote: "Overdrive meter.", source: "Chained Echoes" },
  { quote: "The idol's power.", source: "Case of the Golden Idol" },
  { quote: "Cloudsley.", source: "Case of the Golden Idol" },
  { quote: "Filling in the blanks of a murder.", source: "Case of the Golden Idol" },
  { quote: "Starch Kola.", source: "Shadows of Doubt" },
  { quote: "Fingerprints.", source: "Shadows of Doubt" },
  { quote: "Procedural detective work.", source: "Shadows of Doubt" },
  { quote: "Chai.", source: "Hi-Fi Rush" },
  { quote: "Feel the beat!", source: "Hi-Fi Rush" },
  { quote: "808 the cat.", source: "Hi-Fi Rush" },
  { quote: "You're on a path in the woods.", source: "Slay the Princess" },
  { quote: "Slay the Princess.", source: "Slay the Princess" },
  { quote: "The Voice of the Hero.", source: "Slay the Princess" },
  { quote: "Slow-mo stake.", source: "El Paso, Elsewhere" },
  { quote: "James Savage.", source: "El Paso, Elsewhere" },
  { quote: "Max Payne meets vampires.", source: "El Paso, Elsewhere" },
  { quote: "Perspective shifts.", source: "Viewfinder" },
  { quote: "Photo magic.", source: "Viewfinder" },
  { quote: "Stepping into a polaroid.", source: "Viewfinder" },
  { quote: "Chain hook.", source: "Sanabi" },
  { quote: "Mari.", source: "Sanabi" },
  { quote: "Cyberpunk grapple-hook action.", source: "Sanabi" },
  { quote: "It's pizza time!", source: "Pizza Tower" },
  { quote: "Peppino Spaghetti.", source: "Pizza Tower" },
  { quote: "The anxiety of P-Ranks.", source: "Pizza Tower" },
  { quote: "Aberrations.", source: "Dredge" },
  { quote: "The Marrows.", source: "Dredge" },
  { quote: "Lovecraftian fishing sim.", source: "Dredge" },
  { quote: "Zale and Valere.", source: "Sea of Stars" },
  { quote: "Solstice Warriors.", source: "Sea of Stars" },
  { quote: "Garl the warrior cook.", source: "Sea of Stars" },
  { quote: "The Ballast.", source: "Jusant" },
  { quote: "Climbing the tower.", source: "Jusant" },
  { quote: "Managing stamina on a vertical wall.", source: "Jusant" },
  { quote: "Dead or alive, you're coming with me.", source: "RoboCop: Rogue City" },
  { quote: "Directive 4.", source: "RoboCop: Rogue City" },
  { quote: "I'd buy that for a dollar!", source: "RoboCop: Rogue City" },
  { quote: "The Remnant.", source: "Pacific Drive" },
  { quote: "Olympic Exclusion Zone.", source: "Pacific Drive" },
  { quote: "Kicking your car to fix it.", source: "Pacific Drive" },
  { quote: "B.B. Wand.", source: "Animal Well" },
  { quote: "Disc.", source: "Animal Well" },
  { quote: "The rabbits are watching.", source: "Animal Well" },
  { quote: "Nope!", source: "Balatro" },
  { quote: "Mult.", source: "Balatro" },
  { quote: "Gros Michel.", source: "Balatro" },
  { quote: "The addiction of multiplying scores.", source: "Balatro" },
  { quote: "Mara Forest.", source: "Crow Country" },
  { quote: "Edward Crow.", source: "Crow Country" },
  { quote: "PS1 survival horror nostalgia.", source: "Crow Country" },
  { quote: "Yi.", source: "Nine Sols" },
  { quote: "Apeman.", source: "Nine Sols" },
  { quote: "Taopunk Sekiro.", source: "Nine Sols" },
  { quote: "Red and Antea.", source: "Banishers: Ghosts of New Eden" },
  { quote: "Life to the living, death to the dead.", source: "Banishers: Ghosts of New Eden" },
  { quote: "Haunting choices.", source: "Banishers: Ghosts of New Eden" },
  { quote: "Caz McLeary.", source: "Still Wakes the Deep" },
  { quote: "The Beira D.", source: "Still Wakes the Deep" },
  { quote: "Scottish oil rig terror.", source: "Still Wakes the Deep" },
  { quote: "Defenestration.", source: "Tactical Breach Wizards" },
  { quote: "Zan.", source: "Tactical Breach Wizards" },
  { quote: "Pushing enemies out of windows.", source: "Tactical Breach Wizards" },
  { quote: "Campanella.", source: "UFO 50" },
  { quote: "Baromaze.", source: "UFO 50" },
  { quote: "50 games in 1 collection.", source: "UFO 50" },
  { quote: "Curly.", source: "Mouthwashing" },
  { quote: "Jimmy.", source: "Mouthwashing" },
  { quote: "Space freighter psychological horror.", source: "Mouthwashing" }
];

const filePath = './src/lib/flavorTexts.ts';
let content = fs.readFileSync(filePath, 'utf8');
const match = content.match(/export const MEDIA_FLAVOR_TEXTS: Record<string, FlavorTextEntry\[\]> = (\{[\s\S]*?\});\n\nexport function/);
const obj = eval('(' + match[1] + ')');

let gameArr = obj['Game'] || [];

for (const quoteObj of GAMING_QUOTES) {
  const exists = gameArr.some((entry: any) => {
    if (typeof entry === 'string') return entry === quoteObj.quote;
    return entry.quote === quoteObj.quote;
  });
  
  if (!exists) {
    gameArr.push(quoteObj);
  }
}

obj['Game'] = gameArr;

const exportString = "export const MEDIA_FLAVOR_TEXTS: Record<string, FlavorTextEntry[]> = " + JSON.stringify(obj, null, 2) + ";";
content = content.replace(/export const MEDIA_FLAVOR_TEXTS: Record<string, FlavorTextEntry\[\]> = \{[\s\S]*?\};\n/, exportString + '\n');
fs.writeFileSync(filePath, content);
console.log("Successfully written all hidden gem games!");
