const fs = require('fs');

const uniqueFlavors = {
  "Game": [
    "Skill issue detected.",
    "Git gud casually.",
    "Blaming the controller since 1999.",
    "Just one more turn...",
    "Speedrunning the tutorial.",
    "Mom said it's my turn on the console.",
    "I'm not addicted, I can quit after this boss.",
    "Praising the sun right now.",
    "What a save!",
    "Press F to pay respects to my free time.",
    "Running at a cinematic 24 FPS.",
    "I survived the water level.",
    "Do a barrel roll!",
    "Hey, you, you're finally awake.",
    "I used to be an adventurer like you...",
    "The cake was a lie.",
    "FINISH HIM!",
    "Wasted.",
    "Snake? SNAKE?!",
    "It's super effective!",
    "Checking every corner for secret loot.",
    "Hoarding potions for a final boss that never comes.",
    "My backlog is staring at me.",
    "I didn't lose, it was lag.",
    "Rolling for initiative.",
    "Equipping gear based on stats, not looks. (Or vice versa).",
    "Failing the QTE.",
    "Save scumming my way to victory.",
    "Escort missions are a crime against humanity.",
    "Skipping dialogue and getting lost.",
    "Leveling vigor for once.",
    "No hit run? More like all hit run.",
    "Drop AWP pls.",
    "Rush B do not stop.",
    "The spawn camping is real.",
    "Teabagging the AI.",
    "My framerate is dropping just looking at this.",
    "Over-encumbered and walking back to town.",
    "Fishing minigame > main plot.",
    "Why do I hear boss music?",
    "Objective updated: SURVIVE.",
    "They played us like a damn fiddle!",
    "War... war never changes.",
    "Would you kindly finish this game?",
    "A man chooses, a slave obeys.",
    "Our princess is in another castle.",
    "FUS RO DAH!",
    "Pootis.",
    "Need a dispenser here!",
    "I'm out of mana.",
    "Leeroy Jenkins!!!",
    "50,000 people used to live here...",
    "Remember, no Russian.",
    "Voodoo 1, Viper's on station.",
    "Standby for titanfall.",
    "Rip and tear until it is done.",
    "Hesitation is defeat.",
    "You died.",
    "Bonfire lit.",
    "Humanity restored.",
    "Prey slaughtered.",
    "Enemy missing!",
    "gg ez",
    "Calculated.",
    "No scope 360.",
    "I am Heavy Weapons Guy.",
    "The numbers Mason, what do they mean?!",
    "You have died of dysentery.",
    "Look at this graph.",
    "Not enough minerals.",
    "Spawn more overlords.",
    "Work work.",
    "Zug zug.",
    "Are you winning, son?",
    "Press X to doubt.",
    "Press X to Jason.",
    "Boy.",
    "I need healing!",
    "Stay awhile and listen.",
    "Gotta catch 'em all.",
    "It's dangerous to go alone.",
    "It fills you with determination.",
    "Megalovania starts playing.",
    "Catch a RIIIIIDE!",
    "I'm Commander Shepard, and this is my favorite game on the Citadel.",
    "This was a triumph.",
    "I'm making a note here: HUGE SUCCESS.",
    "Glory to Arstotzka.",
    "Papers, please.",
    "Nothing is true, everything is permitted.",
    "A hunter must hunt.",
    "A hoonter must hoont.",
    "Fear the old blood.",
    "Ah shit, here we go again.",
    "All we had to do, was follow the damn train CJ!",
    "Get over here!",
    "Fatality.",
    "Flawless victory.",
    "Connection lost.",
    "Reconnecting to server...",
    "Server maintenance in 5 minutes."
  ],
  "Book": [
    "Just one more chapter before bed...",
    "Smelling the pages like a weirdo.",
    "My TBR pile is structurally unsound.",
    "I can't, I have to read.",
    "Judging this book precisely by its cover.",
    "The movie was worse.",
    "The book is always better.",
    "Bookmark? I just fold the page (chaotic evil).",
    "Staying up till 4 AM reading in the dark.",
    "Why sleep when there's lore?",
    "The ink is still fresh.",
    "This author feeds on my tears.",
    "I am emotionally compromised by fictional people.",
    "Enemies to lovers trope hitting heavy.",
    "Magic system perfectly balanced.",
    "The hardcover is too heavy to read in bed.",
    "Help, my Kindle died at the climax.",
    "Collecting bookmarks but using a receipt.",
    "The smell of old paper > anything else.",
    "I bought more books instead of reading the ones I have.",
    "Shelf space is just a concept.",
    "Tsundoku master.",
    "The plot armor is exceptionally thick here.",
    "An unreliable narrator? Sign me up.",
    "This exposition is... dense.",
    "Worldbuilding goes brrrrr.",
    "Who needs friends when you have paper characters?",
    "I need a moment to process that plot twist.",
    "Don't talk to me, my favorite character just died.",
    "It was the butler.",
    "A tale as old as time.",
    "Reading slump cured.",
    "Wait, there's a glossary?",
    "Checking the map in the front page for the 100th time.",
    "DNF'ing is self-care.",
    "Five stars, would suffer again.",
    "The prose is purple, but I like purple.",
    "Foreshadowing? Oh, they were cooking.",
    "I highlighted half the page.",
    "The spine is cracked irreparably.",
    "TBR mountain claims another victim.",
    "It was the best of times, it was the worst of times.",
    "Call me Ishmael.",
    "In a hole in the ground there lived a hobbit.",
    "A screaming comes across the sky.",
    "It is a truth universally acknowledged...",
    "All children, except one, grow up.",
    "Mr. and Mrs. Dursley, of number four, Privet Drive, were proud to say...",
    "It was a bright cold day in April.",
    "The man in black fled across the desert.",
    "I am an invisible man.",
    "Happy families are all alike.",
    "You better not never tell nobody but God.",
    "There was a boy called Eustace Clarence Scrubb.",
    "All this happened, more or less.",
    "First lines are hard.",
    "Epilogues are a blessing.",
    "Pacing tighter than my budget.",
    "This magic academy has terrible safety standards.",
    "Oh look, an orphaned farmboy.",
    "The chosen one trope strikes again.",
    "Morally grey? More like pitch black.",
    "The tension is palpable.",
    "Slow burn doing precisely that.",
    "Love triangle? No, give me a polygon.",
    "Found family is the best family.",
    "I demand a sequel.",
    "Why must trilogies have middle book syndrome?",
    "This paperback refuses to stay open.",
    "Crying over 200 pages left.",
    "Dog-earing pages is a crime against humanity.",
    "The dog ate my bookmark.",
    "Library card maxed out.",
    "Bookshelf aesthetics are key.",
    "Aesthetically pleasing typography.",
    "Fonts matter.",
    "Currently reading... since 2021.",
    "Fell asleep and lost my page.",
    "Reading aloud to my cat.",
    "Audiobooks count as reading! Wait, wrong category.",
    "I read this before it was popular on TikTok.",
    "Booktok made me buy it.",
    "Just one more page... *entire book later*",
    "I feel empty now that it's over.",
    "Book hangover mode engaged.",
    "Need a support group for this ending.",
    "The author understood the assignment.",
    "Zero plot, just vibes.",
    "So much angst.",
    "He's a 10 but he's fictional.",
    "I can fix him (I can't).",
    "She's a girlboss, and she's winning.",
    "Murder mystery solved in page 10 (by me).",
    "Red herring caught.",
    "The cliffhanger is illegal.",
    "I will never emotionally recover from this.",
    "Who gave the author the right?",
    "Throwing the book across the room.",
    "Staring blankly at the wall after finishing.",
    "What do I do with my life now?"
  ],
  "Audiobook": [
    "Listening at 2x speed like a sociopath.",
    "The narrator's voice is absolute butter.",
    "Wait, I zoned out for 15 minutes.",
    "Hitting the 'back 30 seconds' button 10 times.",
    "Best enjoyed during a commute.",
    "Doing chores while listening = productivity.",
    "This narrator has 50 different distinct voices.",
    "Audiobook so good I sat in my driveway for 10 mins.",
    "Does this count as reading? Yes.",
    "The chapter transitions are aggressive.",
    "It's like a podcast but with a plot.",
    "Listening in the shower with a waterproof speaker.",
    "Audible hope you enjoyed this program.",
    "Narrator drank water, 0/10 immersion broken.",
    "The background sound effects are... a choice.",
    "Graphic audio hits different.",
    "Listening at 0.5x speed to savor it.",
    "Listening at 3x speed to ascend.",
    "Wait, how do you spell that character's name?",
    "I have no idea what the book cover looks like.",
    "Falling asleep and losing my place permanently.",
    "The sleep timer saved my life.",
    "I can't hear you, I'm deep in the lore.",
    "My earbuds are permanently glued in.",
    "The narrator completely butchered that pronunciation.",
    "When the narrator changes mid-series >:(",
    "Full cast audiobooks are peak cinema.",
    "I speed up the slow parts.",
    "Listening while staring meaningfully out the window.",
    "Are we there yet? No, 5 hours left.",
    "Road trip essential.",
    "This narrator needs an Oscar.",
    "Voice acting > voice reading.",
    "Whispersync is black magic.",
    "My credits are burning a hole in my pocket.",
    "I only buy audiobooks over 30 hours long. Value.",
    "Screaming at the audiobook while driving.",
    "The person next to me in traffic thinks I'm crazy.",
    "Trying to explain to someone I 'listened' to a book.",
    "I'm visually impaired, this is how I read.",
    "A soothing voice narrating sheer horror.",
    "The comedic timing is impecable.",
    "Narrator takes a deep breath *pause*",
    "I can multi-task! (Narrator: They couldn't).",
    "Wait, who's talking now?",
    "The accents are a bit questionable.",
    "The Scottish accent is perfect.",
    "The Irish accent is terrible.",
    "Listening while playing a grindy video game.",
    "Audiobooks = mental background noise.",
    "When the audiobook drops the beat.",
    "Intense orchestral music starts playing.",
    "The volume mixing is terrible.",
    "Why is the narrator whispering?!",
    "WHY IS THE NARRATOR YELLING?!",
    "I need a moment of silence.",
    "Checking my phone to see how much time is left.",
    "The 'Chapter 1' announcement is always too loud.",
    "Narrated by the author! (Sometimes good, sometimes bad).",
    "Memoir read by the person who lived it.",
    "I feel like they're sitting in the room with me.",
    "My headphone battery died at the worst time.",
    "Bluetooth disconnected, now everyone's listening.",
    "I have 12 unfinished audiobooks.",
    "I keep buying them on sale and never listening.",
    "The prologue is 2 hours long.",
    "Epilogue: 5 minutes of silence.",
    "End of disc one.",
    "Please insert disc two.",
    "Cassette tape nostalgia.",
    "CD skips on the bumpy road.",
    "Digital downloads rule.",
    "Libby app is my hero.",
    "Public libraries are goated.",
    "Free audiobooks make me happy.",
    "The narration speed ruins the comedic timing.",
    "Slow down, I'm taking notes!",
    "I can't highlight audio!",
    "Bookmarking the audio is just not the same.",
    "Writing timestamps instead of page numbers.",
    "I miss the smell of pages, but my hands are free.",
    "Listening while running a marathon.",
    "Listening while doing the dishes.",
    "Listening while folding laundry.",
    "Listening while ignoring my responsibilities.",
    "Listening while pretending to work.",
    "Listening in the grocery store.",
    "Listening on the plane.",
    "The ultimate travel companion.",
    "I listen to audiobooks to fall asleep.",
    "I can't fall asleep, this is too good.",
    "The narrator's voice is my sleep paralysis demon now.",
    "I hear the narrator in my thoughts.",
    "Narrator reads the copyright information.",
    "ISBN: 978...",
    "All rights reserved.",
    "Produced by...",
    "Directed by...",
    "The End."
  ],
  "Visual Novel": [
    "Skip unread text? I live dangerously.",
    "Trying to unlock the true ending.",
    "I just want to date the villain.",
    "Wait, this isn't a dating sim!?",
    "Auto-mode on, snacks ready.",
    "The OST is currently slapping.",
    "Bad End 14: You forgot to eat breakfast.",
    "Save scumming every single choice.",
    "Using a walkthrough because I'm dumb.",
    "This route completely destroyed me emotionally.",
    "Yandere detected, deploying evasive maneuvers.",
    "Tsundere levels are off the charts.",
    "Just Monika.",
    "Objection!",
    "Hold it!",
    "Take that!",
    "Hope vs Despair is my daily struggle.",
    "A body has been discovered!",
    "Puhuhu...",
    "I'm not crying, you're crying at this CG.",
    "The gallery is 99% complete, where is the last CG?!",
    "Clicking through the slice-of-life to get to the plot twists.",
    "The plot twist broke my brain.",
    "Time loop mechanics? Sign me up.",
    "El Psy Kongroo.",
    "Tuturu~",
    "I am mad scientist, it's so cool! Sonuvabitch.",
    "Reading this for the plot. Literally.",
    "The UI is surprisingly sleek.",
    "Who voices this character? It sounds familiar.",
    "No voice acting? I must imagine it all.",
    "Partially voiced = weirdly jarring.",
    "The sprites are doing the breathing animation.",
    "When the character stares directly at the 'camera'.",
    "Breaking the fourth wall, are we?",
    "I named the protagonist something stupid.",
    "Why does the protagonist have no eyes?",
    "Ah yes, the faceless protagonist trope.",
    "Childhood friend never wins.",
    "I'm routing for the underdog.",
    "The secret unlockable route.",
    "Playing purely for the meme endings.",
    "The bad endings have the best lore.",
    "Why are the bad endings so detailed?!",
    "Doki Doki gave me trust issues.",
    "Is this a pigeon? No, it's Hatoful Boyfriend.",
    "Fate/stay night is just a cooking game.",
    "People die if they are killed.",
    "The archer class really is made up of archers.",
    "Just because you're correct doesn't mean you're right.",
    "WTC series: Trust no one, not even the cicadas.",
    "When the cicadas cry...",
    "The truth is out there, in another route.",
    "I have 100 save slots and I use them all.",
    "Quick save is my best friend.",
    "Quick load is my savior.",
    "Accidentally clicked the wrong choice, panic ensues.",
    "The affection meter is too obscure.",
    "Need max stats to impress the waifu.",
    "Raising stats via mini-games.",
    "The mini-games are harder than the actual choices.",
    "Why is there a rhythm game in my VN?",
    "Why is there a fighting game in my VN?",
    "Kinetic novel? So it's just a book with pictures.",
    "Kinetic novels are valid, don't @ me.",
    "The pacing is... glacial.",
    "Common route was 30 hours long.",
    "Finally reached a character route.",
    "The true route unlocks after playing everything else.",
    "I 100%'d it. What now?",
    "The fandisk is just pure fluff.",
    "We needed the fluff after that trauma.",
    "Eroge? No, it's literature.",
    "All-ages version cuts out the best plot.",
    "The Steam version is censored.",
    "Applying the restoration patch immediately.",
    "Why is this text box so small?",
    "The font is barely legible.",
    "Default name? Always keep the default name.",
    "Translators are the real heroes.",
    "Machine translation is pure comedy.",
    "The localized jokes are... something.",
    "Reading in the original Japanese to flex.",
    "Kanji dictionary at the ready.",
    "Text hooking software is a lifesaver.",
    "VNDB is my homepage.",
    "Sorting by highest rating on VNDB.",
    "The opening movie goes ridiculously hard.",
    "Never skip the opening.",
    "Never skip the ending song.",
    "The insert song hits right in the feels.",
    "Waiting for the English localization...",
    "It's been 3000 years...",
    "The fan translation patch is finally done!",
    "Kickstarter backer in the credits.",
    "OELVN scene is thriving.",
    "Ren'Py engine carrying the industry.",
    "Unity VNs are getting wild."
  ],
  "Manga": [
    "Reading right to left like a person of culture.",
    "Waiting for the weekly chapter drop.",
    "The hiatus is killing me.",
    "Author is on a break to play Dragon Quest.",
    "Is it a break week?",
    "The cliffhanger was illegal.",
    "The raw scans dropped.",
    "Waiting for the translation group.",
    "This double-page spread is absolute art.",
    "The mangaka's wrists must be in pain.",
    "The art style evolution is insane.",
    "Early chapters look so weird now.",
    "The power scaling makes no sense anymore.",
    "Talk no jutsu is the strongest attack.",
    "Nakama power wins again.",
    "The classic shounen tournament arc.",
    "The training arc.",
    "The beach episode/chapter.",
    "The hot springs episode/chapter.",
    "The obligatory festival scene.",
    "Fireworks drowning out the confession.",
    "Senpai finally noticed.",
    "Truck-kun strikes again.",
    "Reincarnated as a vending machine.",
    "I got reincarnated as a slime.",
    "Iseguy is the strongest.",
    "The protagonist is too OP.",
    "The villain has a sad backstory, I forgive him.",
    "The villain is just pure evil, I love him.",
    "Did he just solo the entire verse?",
    "Bankai.",
    "Domain Expansion.",
    "Stand cry goes here.",
    "NANI?!",
    "Omae wa mou shindeiru.",
    "Yare yare daze.",
    "Kono Dio da!",
    "It was me, Dio!",
    "Ho, you're approaching me?",
    "I can't beat the shit out of you without getting closer.",
    "Za Warudo!",
    "Equivalent exchange.",
    "Ed...ward...",
    "Too soon.",
    "The One Piece is real!",
    "Gomu Gomu no...",
    "Dattebayo!",
    "Believe it!",
    "Kamehameha!",
    "Over 9000!",
    "I will become the Pirate King!",
    "I will become the Hokage!",
    "Plus Ultra!",
    "Detroit Smash!",
    "Eren did nothing wrong.",
    "Tatakae.",
    "Give up your dreams and die.",
    "Susume!",
    "The rumbling.",
    "Seinen hits different.",
    "Shojo eyes are taking up 90% of the face.",
    "Josei speaks to my soul.",
    "The slice of life is healing me.",
    "The psychological horror is breaking me.",
    "The romcom misunderstandings are frustrating.",
    "Just COMMUNICATE!",
    "He's dense as a neutron star.",
    "She's too tsundere for her own good.",
    "The childhood friend finally won?!",
    "The main couple established in chapter 10?!",
    "Reiwa era manga is built different.",
    "We don't need 200 chapters for a handhold.",
    "Handholding? How lewd.",
    "The paneling is confusing.",
    "I read this panel right to left, then left to right.",
    "Four-koma (4-panel) manga is peak comedy.",
    "Gag manga relies on me not thinking.",
    "Webtoons count, right?",
    "Scrolling down endlessly.",
    "The long vertical strip format.",
    "Buying physical volumes to support the creator.",
    "My bookshelf is sagging from all the omnibuses.",
    "The box set was totally worth the money.",
    "The spine art connects!",
    "The author's notes are hilarious.",
    "The Q&A section (SBS) has actual lore.",
    "Sketch pages in the volume extras.",
    "Volume cover goes incredibly hard.",
    "Color pages are a blessing.",
    "I wish it had an anime adaptation.",
    "The anime ruined the pacing.",
    "The manga was better.",
    "Read the manga.",
    "They skipped the best arc!",
    "Anime-original ending was trash.",
    "We ignore the live-action movie.",
    "Never bring up the live-action.",
    "The cosplay will be amazing."
  ],
  "Series": [
    "Just one more episode...",
    "Netflix: Are you still watching? Me: Do not judge me.",
    "Skipping the intro to save 1:30 per episode.",
    "Never skipping the intro because it's a banger.",
    "The recap is longer than the episode.",
    "Previously on...",
    "Next time on...",
    "Ending on a cliffhanger should be illegal.",
    "The season finale ruined me.",
    "The series finale ruined the whole show.",
    "Season 8 doesn't exist.",
    "We don't talk about season 8.",
    "It gets better in season 3, I swear.",
    "The pilot was rough.",
    "Binge-watching 10 hours straight.",
    "I need to pee but I can't pause.",
    "The aesthetic of this show is my entire personality now.",
    "I base my outfits on this character.",
    "I have a parasocial relationship with this cast.",
    "The ship is sailing!",
    "My ship sank.",
    "They are endgame.",
    "Will they, won't they?",
    "THEY DID!",
    "The slow burn paid off.",
    "The banter is top-notch.",
    "Sitcom laugh track intensifies.",
    "Single-camera comedy supremacy.",
    "The mockumentary look.",
    "Looking directly into the camera like Jim Halpert.",
    "That's what she said.",
    "Bears. Beets. Battlestar Galactica.",
    "Identity theft is not a joke, Jim!",
    "PIVOT!",
    "We were on a break!",
    "How you doin'?",
    "Could I BE any more...",
    "Smelly cat, smelly cat...",
    "Bazinga! (ironically).",
    "Title of your sex tape.",
    "Cool cool cool cool cool. No doubt no doubt no doubt.",
    "Nine-Nine!",
    "Treat yo self.",
    "Parks and Rec is just optimistic Office.",
    "Winter is coming.",
    "The Lannisters send their regards.",
    "I drink and I know things.",
    "You know nothing, Jon Snow.",
    "Dracarys.",
    "Not great, not terrible. (3.6 Roentgen).",
    "I am the danger.",
    "I am the one who knocks.",
    "Say my name.",
    "Yeah, science!",
    "It's never lupus.",
    "Everybody lies.",
    "The truth is out there.",
    "Trust no one.",
    "I want to believe.",
    "Wubba lubba dub dub!",
    "I turned myself into a pickle!",
    "To be fair, you have to have a very high IQ to understand...",
    "In the criminal justice system...",
    "Dun dun.",
    "This is the way.",
    "I have spoken.",
    "Baby Yoda is the cutest.",
    "Beam me up, Scotty.",
    "Live long and prosper.",
    "Resistance is futile.",
    "Make it so.",
    "It's bigger on the inside.",
    "Wibbly wobbly, timey wimey.",
    "Exterminate!",
    "Delete!",
    "Allons-y!",
    "Geronimo!",
    "Bow ties are cool.",
    "The cake is a lie. Wait, wrong medium.",
    "Who killed Laura Palmer?",
    "The owls are not what they seem.",
    "Damn fine cup of coffee.",
    "Lost had perfectly answered mysteries. (Lie).",
    "We have to go back!",
    "Not Penny's boat.",
    "The numbers are bad.",
    "Clear eyes, full hearts, can't lose.",
    "Texas forever.",
    "Stranger Things is just 80s nostalgia.",
    "Justice for Barb.",
    "The Upside Down.",
    "Running up that hill.",
    "Black Mirror making me fear my toaster.",
    "What if phones, but too much?",
    "Succession is just rich people yelling.",
    "L to the OG.",
    "Boar on the floor.",
    "You can't make a Tomlette without breaking some Greggs.",
    "The Bear gives me anxiety.",
    "Yes, Chef!",
    "Behind!",
    "Corner!",
    "Heard, Chef."
  ],
  "Movie": [
    "Absolute cinema.",
    "Kino is served.",
    "Martin Scorsese approves.",
    "It insists upon itself.",
    "Sitting through the credits for a 3-second post-credit scene.",
    "The popcorn didn't make it past the trailers.",
    "Shushing people in the theater.",
    "The IMAX experience.",
    "Dolby Atmos shaking my seat.",
    "The Snyder Cut was better.",
    "Release the director's cut!",
    "The theatrical cut is a mess.",
    "The book was better, but the movie was okay.",
    "The practical effects > CGI.",
    "CGI has aged like milk.",
    "The Wilhelm scream.",
    "Lens flare intensifies.",
    "(Directed by J.J. Abrams).",
    "Explosions everywhere.",
    "(Directed by Michael Bay).",
    "Mind-bending plot.",
    "(Directed by Christopher Nolan).",
    "Symmetrical framing.",
    "(Directed by Wes Anderson).",
    "Lots of dialogue and feet.",
    "(Directed by Quentin Tarantino).",
    "Spooky and gothic.",
    "(Directed by Tim Burton).",
    "Twist ending that ruins everything.",
    "(Directed by M. Night Shyamalan).",
    "I see dead people.",
    "What a twist!",
    "Rosebud.",
    "We're gonna need a bigger boat.",
    "Here's looking at you, kid.",
    "May the Force be with you.",
    "I am your father.",
    "No, I am your father.",
    "I'll be back.",
    "Hasta la vista, baby.",
    "Get to the chopper!",
    "E.T. phone home.",
    "There's no place like home.",
    "Toto, I've a feeling we're not in Kansas anymore.",
    "I'm the king of the world!",
    "Draw me like one of your French girls.",
    "There was room on the door for Jack.",
    "My precious.",
    "You shall not pass!",
    "One does not simply walk into Mordor.",
    "And my axe!",
    "Fly, you fools!",
    "I love the smell of napalm in the morning.",
    "Say hello to my little friend!",
    "You can't handle the truth!",
    "I'm going to make him an offer he can't refuse.",
    "Leave the gun, take the cannoli.",
    "To infinity and beyond!",
    "You've got a friend in me.",
    "Hakuna Matata.",
    "Life finds a way.",
    "Clever girl.",
    "Welcome to Jurassic Park.",
    "We spared no expense.",
    "I am Iron Man.",
    "Avengers, assemble.",
    "I love you 3000.",
    "I don't feel so good.",
    "Perfectly balanced, as all things should be.",
    "Why did you say that name?!",
    "Do you bleed? You will.",
    "I'm Batman.",
    "Why so serious?",
    "Some men just want to watch the world burn.",
    "Ogres are like onions.",
    "Get out of my swamp!",
    "Somebody once told me...",
    "First rule of Fight Club...",
    "The first rule of Fight Club is...",
    "I am Jack's complete lack of surprise.",
    "Where is my mind?",
    "The Matrix has you.",
    "There is no spoon.",
    "Red pill or blue pill?",
    "I know kung fu.",
    "Show me the money!",
    "You had me at hello.",
    "I feel the need... the need for speed.",
    "Nobody puts Baby in a corner.",
    "I'll have what she's having.",
    "Houston, we have a problem.",
    "Keep your friends close, but your enemies closer.",
    "As far back as I can remember, I always wanted to be a gangster.",
    "Funny how? Like I'm a clown? I amuse you?",
    "You talkin' to me?",
    "Here's Johnny!",
    "All work and no play makes Jack a dull boy.",
    "Redrum.",
    "The power of Christ compels you!",
    "Do you like scary movies?",
    "Whatever you do, don't fall asleep.",
    "A census taker once tried to test me."
  ],
  "Comic": [
    "It's not a comic, it's a graphic novel.",
    "Waiting for the trade paperback.",
    "The single issues are taking up all my space.",
    "Bagging and boarding.",
    "The variant cover is too expensive.",
    "Holo-foil embossed cover.",
    "Number 1 issue collector.",
    "The continuity is a complete mess.",
    "Time for another reboot!",
    "New 52 or Rebirth?",
    "Marvel NOW or All-New All-Different?",
    "The retcon makes no sense.",
    "Nobody stays dead in comics.",
    "Except Uncle Ben.",
    "With great power comes great responsibility.",
    "I am Vengeance. I am the Night.",
    "Up, up, and away!",
    "Snikt!",
    "Thwip!",
    "Bamf!",
    "The multiverse is getting complicated.",
    "Crisis on Infinite Earths.",
    "Secret Wars.",
    "Event fatigue is real.",
    "Tie-in issues are a scam.",
    "The art style changed mid-arc and I hate it.",
    "The penciler is carrying this book.",
    "The inker ruined the pencils.",
    "The colorist doesn't get enough credit.",
    "Lettering: Comic Sans (just kidding).",
    "Speech bubbles covering the best art.",
    "Splash page perfection.",
    "Two-page spread hitting hard.",
    "The panels flow so nicely.",
    "Alan Moore hates this adaptation.",
    "Grant Morrison is doing magic again.",
    "Stan Lee cameo (in spirit).",
    "Excelsior!",
    "Jack Kirby is king.",
    "Frank Miller's noir grit.",
    "Todd McFarlane's extremely long capes.",
    "Rob Liefeld's pouches and lack of feet.",
    "Jim Lee's crosshatching.",
    "Alex Ross paints like a god.",
    "Indie comics are where the real story is.",
    "Image Comics supremacy.",
    "Dark Horse bringing the spooky vibes.",
    "Vertigo is missed.",
    "Reading The Sandman again.",
    "Watchmen is a masterpiece.",
    "Who watches the Watchmen?",
    "V for Vendetta.",
    "Remember, remember, the 5th of November.",
    "Batman could beat anyone with prep time.",
    "Superman is boring (You're wrong).",
    "Spider-Man's life is just suffering.",
    "Parker luck.",
    "Mutants are hated and feared.",
    "Magneto was right.",
    "To me, my X-Men.",
    "The Avengers are just cops.",
    "The Justice League is a pantheon.",
    "Kryptonite is a lazy plot device.",
    "Yellow rings? Seriously?",
    "In brightest day, in blackest night...",
    "Wakanda Forever.",
    "Hulk smash!",
    "I'm the best there is at what I do.",
    "And what I do isn't very nice.",
    "Sweet Christmas!",
    "My spider-sense is tingling.",
    "Avengers Assemble!",
    "Flame on!",
    "It's clobberin' time!",
    "By the hoary hosts of Hoggoth!",
    "Imperius Rex!",
    "Hail Hydra.",
    "The Joker's society speech.",
    "We live in a society.",
    "It takes one bad day.",
    "The killing joke.",
    "Death in the family.",
    "Crowbar noises.",
    "Robin died again.",
    "How many Robins are there?",
    "Nightwing's butt is canon.",
    "Flashpoint ruined everything.",
    "Barry Allen needs to stop messing with the timeline.",
    "It was me, Barry!",
    "Reverse Flash is petty AF.",
    "Lex Luthor stole 40 cakes. That's terrible.",
    "Darkseid is.",
    "Anti-Life justifies my hate.",
    "Comic Book Guy: Worst. Issue. Ever.",
    "Checking CBR for previews.",
    "Pull list at the local comic shop.",
    "Support your LCS!",
    "Free Comic Book Day!",
    "Cosplaying at comic con."
  ]
};

let code = fs.readFileSync('src/lib/flavorTexts.ts', 'utf8');

// 1. Strip the old MEME_EXPANSIONS logic
const startMemes = code.indexOf('\n// Meme and Shitpost expansions');
const endMemes = code.indexOf('};\n', startMemes);
if (startMemes !== -1 && endMemes !== -1) {
    code = code.slice(0, startMemes) + code.slice(endMemes + 3);
}

// 2. Build the unique block
let addedContent = `\n// Unique Meme and Shitpost expansions (100 per category)\nconst MEME_EXPANSIONS: Record<string, string[]> = {\n`;

for (const [type, lines] of Object.entries(uniqueFlavors)) {
  addedContent += `  "${type}": [\n`;
  for (const line of lines) {
    // Escape backticks if needed
    addedContent += `    \`${line.replace(/`/g, '\\\\`')}\`,\n`;
  }
  addedContent += `  ],\n`;
}
addedContent += `};\n`;

// 3. Insert it before GENERIC_EXPANSIONS
const tIndex = code.indexOf('const GENERIC_EXPANSIONS');
if (tIndex !== -1) {
  code = code.slice(0, tIndex) + addedContent + '\\n' + code.slice(tIndex);
}

fs.writeFileSync('src/lib/flavorTexts.ts', code);
console.log("Updated flavorTexts.ts with completely unique templates!");
