import fs from "fs";

const GAMING_QUOTES = [
  "BOOM! Tetris for Jonas.", "Line piece!",
  "Our princess is in another castle!", "1-UP!",
  "It's dangerous to go alone! Take this.",
  "Warp whistle secret.", "Tanooki suit.",
  "Reticulating splines.",
  "Yoshi sacrifice jump.",
  "You fight like a dairy farmer!", "How appropriate. You fight like a cow!", "Look behind you, a Three-Headed Monkey!",
  "Shoryuken!", "Hadouken!", "Sonic Boom!", "TIGER UPPERCUT!",
  "Gotta go fast!", "Blast processing.",
  "Welcome to the Dark World.", "Master Sword GET!",
  "Our words are backed with NUCLEAR WEAPONS!", "Gandhi has declared war!",
  "Get over here!", "Fatality.", "Flawless victory.", "Toasty!",
  "IDDQD", "IDKFA",
  "Bring me the blue pages...", "Bring me the red pages...",
  "Save the animals?", "The baby...",
  "Banana slamma!", "Minecart madness.",
  "But you're still hungry.", "The black wind howls...",
  "Smell ya later!", "MissingNo.", "It's super effective!",
  "So long, gay Bowser!", "BLJ up the stairs.",
  "Jill sandwich.", "Itchy, tasty.", "Master of unlocking.",
  "Locking the butler in the freezer.", "Swan dive!",
  "Stay a while and listen.", "Fresh meat!",
  "Aerith...", "Omnislash!", "This guy are sick.", "Let's mosey.",
  "Do a barrel roll!", "Can't let you do that, Star Fox!",
  "What is a man? A miserable little pile of secrets!", "Die monster!",
  "No Oddjob allowed.", "Slappers only!", "Paintball mode.",
  "War. War never changes.",
  "Hey! Listen!", "Water Temple PTSD.",
  "They're waiting for you, Gordon. In the test chamber.", "Wake up, Mr. Freeman.",
  "SNAKE? SNAAAAKE!", "A Hind D?", "Psycho Mantis...?", "You like Castlevania, don't you?",
  "You must construct additional pylons.", "Nuclear launch detected.", "Zerg rush!", "My life for Aiur!",
  "Go for the eyes, Boo!", "You must gather your party before venturing forth.",
  "My scythe... I like to keep it where my heart used to be.", "Run you pigeons, it's Robert Frost!",
  "L-l-look at you, hacker.", "Glory to the mass.",
  "The fear of blood tends to create fear for the flesh.",
  "FALCON PUNCH!", "WOMBO COMBO!", "That ain't Falco.",
  "Rush B", "Bomb has been planted.", "Fire in the hole!",
  "What a shame.", "I never asked for this.",
  "Removing the pool ladder.", "Rosebud.",
  "Not even death can save you from me.", "Moo moo, moo moo moo.",
  "I need a weapon.", "Wort wort wort.",
  "Leave me alone!", "Here we go again.",
  "In my restless dreams, I see that town.", "There was a hole here. It's gone now.",
  "No items, Fox only, Final Destination.", "Wavedashing.",
  "Fission Mailed.", "I need scissors! 61!", "The La Li Lu Le Lo?",
  "Scanning approach.", "Chozo Ghosts.",
  "Sploosh! Kaboom!",
  "Tommy Vercetti... Remember the name!", "Lance Vance Dance.",
  "Meatbag.", "I am Revan.", "Statement: HK-47 is ready to serve.",
  "LEEROY JENKINS!", "More dots!", "Lok'tar Ogar!",
  "The right man in the wrong place can make all the difference.", "Pick up that can.", "We don't go to Ravenholm.",
  "What a thrill...", "You're pretty good.", "The feeding of the tree frog...",
  "All you had to do was follow the damn train, CJ!", "Ah shit, here we go again.",
  "Sir, finishing this bite.", "To give the Covenant back their bomb.",
  "What're ya buyin?", "What're ya sellin?", "Leon, help!", "No thanks, bro.",
  "Agro!",
  "ARES! Destroy my enemies, and my life is yours!", "ZEUS!",
  "Baba Yetu.",
  "Stop right there, criminal scum!", "By Azura, by Azura, by Azura!", "Have you heard of the high elves?",
  "Matt is the final boss.", "Nice spare.",
  "Would you kindly?", "No gods or kings. Only man.", "Welcome to Rapture.",
  "The cake is a lie.", "This was a triumph.", "I'm making a note here: HUGE SUCCESS.",
  "Pootis.", "Spy around here!", "Professionals have standards.", "Meet the Medic.",
  "Fifty thousand people used to live here. Now it's a ghost town.", "Mission failed, we'll get 'em next time.",
  "Rosalina.", "Super Guide.",
  "I should go.", "I'm Commander Shepard, and this is my favorite store on the Citadel.", "Calibrations.",
  "Hey cousin, let's go bowling!",
  "Tunnel Snakes rule!", "Democracy is non-negotiable.",
  "PILLS HERE!", "Tank!", "Grabbin' peels.",
  "Marco Polo.",
  "Umbasa.", "So the world might be mended.", "Heart of gold.",
  "Assuming direct control.", "I am the very model of a scientist Salarian.",
  "My name is John Marston!",
  "The truth is, the game was rigged from the start.", "Patrolling the Mojave almost makes you wish for a nuclear winter.", "Ring-a-ding-ding!",
  "Creeper? Aww man.", "Never dig straight down.", "Diamonds!",
  "I used to be an adventurer like you, then I took an arrow in the knee.", "FUS RO DAH!", "Do you get to the Cloud District very often?",
  "Praise the sun!", "Git gud.", "Amazing chest ahead.", "Try jumping.",
  "I am a potato.", "When life gives you lemons, don't make lemonade.", "SPAAAAACE!",
  "Protocol 10 will commence in X hours.",
  "Chirp.", "Walking in the snow.",
  "Do you like hurting other people?",
  "Yee-yee ass haircut.", "Wasted.",
  "Endure and survive.", "Swear to me.", "Clickers.",
  "Bring us the girl, and wipe away the debt.", "He doesn't row.", "Booker, catch!",
  "A hunter is a hunter, even in a dream.", "Fear the old blood.", "Grant us eyes.",
  "Wind's howling.", "How about a round of Gwent?", "Pam pa ram, pam pam pa ram.",
  "You're gonna have a bad time.", "Despite everything, it's still you.", "It fills you with determination.",
  "I need healing!", "Nerf this!", "Ryu ga waga teki wo kurau!", "It's high noon.",
  "The blob.",
  "Abigail eats quartz.", "Grandpa's bed.", "Prismatic Shard.",
  "Rip and tear, until it is done.", "BFG 9000.",
  "Yahaha! You found me!", "Durian farming.", "Mipha's Grace is ready.",
  "This cannot continue.", "Become as Gods.", "Glory to mankind.",
  "Bapanada.", "Git gud!", "SHAW!", "No mind to think.",
  "Boy.", "Read it, boy.", "We must be better.",
  "I have a plan, Arthur!", "Tahiti!", "LENNY!", "Mangoes.",
  "Mr. Evrart is helping me find my gun.", "I am a feminist.", "Hobocop.",
  "There is no escape.", "Blood and darkness!", "Bouldy believes in you.",
  "Maidenless.", "Try fingers, but hole.", "Let me solo her.", "Put these foolish ambitions to rest.",
  "I am a romance option.", "Authority.", "I can fix him.", "Ignis!", "Chk!"
];

const fileContent = fs.readFileSync("./src/lib/flavorTexts.ts", "utf-8");
const jsonStr = fileContent.match(/export const MEDIA_FLAVOR_TEXTS: Record<string, string\[\]> = (\{[\s\S]*?\});/);
const parsed = JSON.parse(jsonStr[1]);

const existingGames = parsed.Game || [];
const combined = [...existingGames, ...GAMING_QUOTES];
parsed.Game = Array.from(new Set(combined));

const exportString = `export const MEDIA_FLAVOR_TEXTS: Record<string, string[]> = ${JSON.stringify(parsed, null, 2)};\n` +
`\nexport function getRandomFlavorText(type: string): string {\n  if (!type || !MEDIA_FLAVOR_TEXTS[type] || MEDIA_FLAVOR_TEXTS[type].length === 0) {\n    return 'A classic masterpiece.';\n  }\n  const texts = MEDIA_FLAVOR_TEXTS[type];\n  return texts[Math.floor(Math.random() * texts.length)];\n}\n`;

fs.writeFileSync("./src/lib/flavorTexts.ts", exportString);
console.log("Appended game quotes!");
