const fs = require('fs');
const genres = [
  "Action", "Adventure", "RPG", "JRPG", "WRPG", "Strategy", "RTS", "Turn-Based Strategy",
  "Simulation", "Sports", "Racing", "Fighting", "Platformer", "Shooter", "FPS", "TPS",
  "Puzzle", "Survival", "Horror", "Survival Horror", "Stealth", "Rhythm", "Visual Novel",
  "Point-and-Click", "Sandbox", "Open World", "MMO", "MMORPG", "MOBA", "Battle Royale",
  "Card Game", "Board Game", "Trivia", "Party", "Educational", "Interactive Fiction",
  "FMV", "Metroidvania", "Roguelike", "Roguelite", "Tower Defense", "Auto Battler",
  "Shoot 'em Up", "Beat 'em Up", "Hack and Slash", "Drama", "Comedy", "Romance", "Erotic",
  "Historical", "Sci-Fi", "Fantasy", "Mystery", "Thriller", "Superhero", "Anime"
];

const tags = [
  "2D", "3D", "Pixel Art", "Voxel", "Realistic", "Cel-shaded", "Text-Based", "Isometric",
  "Top-Down", "Side-Scroller", "First-Person", "Third-Person",
  "Singleplayer", "Multiplayer", "Co-op", "Local Co-op", "Online Co-op", "PvP", "PvE",
  "Controller Support", "VR", "AR", "Touch Controls",
  "Early Access", "Free to Play", "Microtransactions", "Loot Boxes", "Gacha", "Season Pass",
  "Story Rich", "Lore-Rich", "Multiple Endings", "Choices Matter", "Branching Narrative",
  "Character Customization", "Skill Tree", "Classes", "Leveling System", "Loot",
  "Female Protagonist", "Male Protagonist", "Silent Protagonist", "Custom Protagonist", "Multiple Protagonists",
  "Moddable", "Level Editor", "Procedural Generation", "Permadeath", "Ironman Mode",
  "Crafting", "Base Building", "Resource Management", "Trading", "Economy", "Automation",
  "Turn-Based Combat", "Real-Time Combat", "Tactical", "Action Combat", "Hack and Slash",
  "Souls-like", "Metroidvania", "Bullet Hell", "Twin Stick Shooter",
  "Post-Apocalyptic", "Cyberpunk", "Steampunk", "Dieselpunk", "Solarpunk",
  "Space", "Aliens", "Zombies", "Vampires", "Werewolves", "Demons", "Dragons", "Monsters",
  "Magic", "Mechs", "Robots", "AI", "Time Travel", "Alternate History", "Mythology",
  "War", "WWI", "WWII", "Cold War", "Modern Military", "Historical Fiction",
  "Dark Fantasy", "High Fantasy", "Low Fantasy", "Urban Fantasy", "Sword and Sorcery",
  "Humor", "Satire", "Parody", "Emotional", "Relaxing", "Cozy", "Wholesome",
  "Difficult", "Easy", "Casual", "Hardcore", "Family Friendly",
  "Gore", "Violent", "Nudity", "Sexual Content", "NSFW", "Psychological Horror", "Jump Scares",
  "Cute", "Colorful", "Dark", "Gritty", "Atmospheric", "Cinematic", "Surreal", "Trippy",
  "Great Soundtrack", "Dynamic Music", "Voice Acting", "Full Voice Acting", "Silent",
  "Retro", "Arcade", "Remake", "Remaster", "Reboot", "Sequel", "Prequel", "Spin-off",
  "Physics", "Destruction", "Parkour", "Flight", "Driving", "Sailing", "Swimming",
  "Stealth", "Cover System", "QTEs", "Quick Time Events", "Boss Fights",
  "Fishing", "Farming", "Mining", "Cooking", "Hunting", "Gathering", "Survival Elements",
  "Dating Sim", "Romance Options", "NTR", "Otome", "BL", "GL", "Yuri", "Yaoi", "Harem", "Reverse Harem",
  "Isekai", "Mecha", "Magical Girl", "Slice of Life", "Coming of Age", "Tragedy", "Drama",
  "Investigation", "Detective", "Crime", "Heist", "Assassination", "Mystery Solving",
  "Politics", "Diplomacy", "Espionage", "Cyber Warfare",
  "Superheroes", "Villains", "Anti-Hero", "Morally Gray", "Corruption", "Rebellion",
  "Side Quests", "Minigames", "Collectathon", "Speedrun", "Score Attack", "Time Attack",
  "New Game Plus", "Endgame Content", "Post-Game", "Grindy", "Replay Value", "Short", "Long",
  "Award Winning", "Critically Acclaimed", "Cult Classic", "Indie", "AAA", "AA",
  "Kickstarted", "Crowdfunded", "Esports", "Competitive", "Ranked", "Leaderboards",
  "Asynchronous Multiplayer", "Cross-Platform", "Cloud Gaming", "DRM-Free",
  "Episodic", "Live Service", "MMO", "Hub World", "Dungeon Crawler", "Grid-Based",
  "Deckbuilder", "Drafting", "Card Battler", "Dice Rolling", "Worker Placement",
  "Party Game", "Minigame Collection", "Rhythm-Based", "Music Generation",
  "Educational", "Typing", "Programming", "Math", "Language Learning",
  "Historical Accuracy", "Documentary", "Biographical",
  "Psychological", "Philosophical", "Subversive", "Meta", "Fourth Wall Break",
  "Lovecraftian", "Eldritch", "Cosmic Horror", "Gothic", "Victorian", "Medieval", "Feudal",
  "Western", "Pirates", "Ninjas", "Samurai", "Martial Arts", "Wrestling", "Boxing",
  "Soccer", "Football", "Basketball", "Baseball", "Golf", "Tennis", "Extreme Sports",
  "Skateboarding", "Snowboarding", "Surfing", "BMX", "Racing Simulation", "Arcade Racing",
  "Flight Simulator", "Space Sim", "Train Simulator", "Farming Simulator", "Life Sim",
  "God Game", "City Builder", "Colony Sim", "Management", "Tycoon", "Idle", "Clicker",
  "Merge", "Match 3", "Hidden Object", "Solitaire", "Mahjong", "Sudoku", "Crossword",
  "Jigsaw", "Logic Puzzle", "Physics Puzzle", "Word Game", "Trivia", "Quiz"
];

fs.writeFileSync('taxonomy.json', JSON.stringify({genres, tags}));
