export const MEDIA_FLAVOR_TEXTS: Record<string, string[]> = {
  Game: [
    "Just one more turn.", "Rolling for initiative.", "Praising the sun.", "Press F to pay respects.",
    "The cake is a lie.", "It's dangerous to go alone.", "Wasted.", "You died.", "Finish him!",
    "Do you guys not have phones?", "Hey, you, you're finally awake.", "Would you kindly?",
    "War. War never changes.", "I used to be an adventurer like you.", "A winner is you!",
    "It's a-me!", "Snake? Snake?! SNAAAAKE!", "Nothing is true, everything is permitted.",
    "I need a weapon.", "Pootis.", "Rip and tear, until it is done.", "Get over here!",
    "Our princess is in another castle.", "Boy.", "Stay awhile and listen.", "All your base are belong to us.",
    "Do a barrel roll!", "Thank you Dark Souls.", "FUS RO DAH!", "What is a man? A miserable little pile of secrets.",
    "I survived the Gulag.", "They played us like a damn fiddle!", "Sir, finishing this bite.",
    "I'm Commander Shepard, and this is my favorite store on the Citadel.", "Waka waka waka.",
    "Look behind you, a three-headed monkey!", "The right man in the wrong place can make all the difference.",
    "You have died of dysentery.", "Rise and shine, Mr. Freeman.", "No gods or kings, only man.",
    "I am Error.", "A delayed game is eventually good.", "This was a triumph.", "You must construct additional pylons.",
    "Zug zug.", "Leeroy Jenkins!", "Time to kick ass and chew bubble gum.", "What are you buying?",
    "Hesitation is defeat.", "Remember, no Russian.", "Standby for Titanfall.", "Protocol 3: Protect the Pilot.",
    "Nanomachines, son!", "I should go.", "Whether we wanted it or not, we've stepped into a war with the Cabal on Mars.",
    "Eyes up, Guardian.", "Wake me when you need me.", "Bravo Six, going dark.", "I need healing!",
    "Stop poking me!", "Work, work.", "Something need doing?", "Endure and survive.",
    "Suck it down.", "I'll have two number 9s...", "We're made of block.", "Gotta catch 'em all!",
    "It's super effective!", "Nuclear launch detected.", "Job's done.", "Ready to work.",
    "My life for Aiur!", "You require more vespene gas.", "Spyin' on my sentry!", "Need a dispenser here!",
    "I never asked for this.", "Praise Geraldo.", "Wind's howling.", "Hmm, medallion's humming.",
    "How about a round of Gwent?", "Bloodborne PC port when?", "Half-Life 3 confirmed.", "Do a flip!",
    "Jason!", "Shaun!", "Press X to Jason.", "The bomb has been planted.", "Terrorists win.",
    "Counter-Terrorists win.", "Rush B.", "Cyka blyat.", "gg wp", "EZ", "No re", "It's high noon.",
    "Justice rains from above!", "Ryūjin no ken wo kurae!", "Heroes never die!", "Nerf this!",
    "Catch a RIDE!", "I'm the conductor of the poop train!", "Keep your expectations low, boy.",
    "Lumbago.", "I have a plan, Arthur.", "Tahiti.", "We just need more money.", "Git gud.",
    "You must gather your party before venturing forth.", "Stop right there criminal scum!", 
    "Would you like to save?", "I am overgrown with moss.", "Bapanada.", "No cost too great.",
    "It fills you with determination.", "Get dunked on.", "Hey, listen!", "Do you like hurting other people?",
    "A man chooses, a slave obeys.", "SHAW!", "Stand in the ashes of a trillion dead souls...",
    "Sir, Isaac Newton is the deadliest son of a bitch in space!", "Take my money!", 
    "You forget a thousand things every day, pal.", "Requiescat in pace.", "I survive.", "Wololo.",
    "The factory must grow.", "You've met with a terrible fate, haven't you?", "There's more to explore here.",
    "50,000 people used to live here.", "I am Malenia, Blade of Miquella.", "Try fingers, but hole.",
    "Maidenless.", "Let me solo her.", "A hoonter must hoont.", "Fear the old blood.", "Praise the message!",
    "Ah shit, here we go again.", "All you had to do was follow the damn train, CJ!", "EA Sports, it's in the game.",
    "SEGA!", "FALCON PUNCH!", "Show me your moves!", "The president has been kidnapped by ninjas.",
    "I am sworn to carry your burdens.", "Do you get to the Cloud District very often?", 
    "Look at this net, that I just found.", "Wait, that's illegal.", "Creeper, aw man.", 
    "The diamond pickaxe.", "Building a dirt hut.", "Never dig straight down.", "Redstone engineering.",
    "The RNG gods frown upon me.", "F2P BTW.", "Pay to win.", "Save scumming.", "Speedrun strats.",
    "Any% glitchless.", "Frame perfect input.", "Wavedashing.", "L-Cancel.", "No items, Fox only, Final Destination.",
    "I am Heavy Weapons Guy.", "That spy is a spy!", "MEDIC!", "Overwatch needs a healer.", "C9!",
    "I'm not a moron!", "The Enrichment Center reminds you...", "I'm making a note here: HUGE SUCCESS.",
    "It's hard to overstate my satisfaction.", "I gently open the door.", "Dormammu, I've come to bargain.", 
    "The Cole Train runs on whole grain!", "Dom! No!", "Reticulating splines.", "Sul sul!", "Deg deg!",
    "Motherlode.", "Rosebud.", "Entering cheat codes.", "Up up down down left right left right B A Start.",
    "IDDQD", "IDKFA", "Glory to Arstotzka.", "Cause no trouble.", "Papers, please.", "Catch phrase!",
    "Against all the evil that Hell can conjure...", "Rip and tear, until it is done.", "Shoot it until it dies.",
    "BFG 9000.", "I survived the horrors of the Spencer Mansion.", "Jill sandwich.", 
    "You were almost a Jill sandwich!", "What're ya buyin', stranger?", "Leeeeooon!", 
    "I'm gonna take you for a ride!", "Mango Sentinel.", "Mahvel baybee!", "Combo breaker!", 
    "C-C-C-Combo Breaker!", "Flawless victory.", "Babality.", "Animality.", "Fatality."
  ],
  Book: [
    "Just one more chapter.", "The smell of old paper.", "So many books, so little time.",
    "It was the best of times, it was the worst of times.", "Call me Ishmael.", 
    "In a hole in the ground there lived a hobbit.", "Reader, I married him.",
    "The man in black fled across the desert, and the gunslinger followed.", 
    "All children, except one, grow up.", "It is a truth universally acknowledged...",
    "Happy families are all alike.", "I am haunted by humans.", "Big Brother is watching you.",
    "Not all those who wander are lost.", "To be or not to be.", "Frankly, my dear, I don't give a damn.",
    "Words are our most inexhaustible source of magic.", "Don't panic.", 
    "I must not fear. Fear is the mind-killer.", "The building was on fire, and it wasn't my fault.",
    "It is important, when killing a nun, to ensure that you bring an army of sufficient size.",
    "The sky above the port was the color of television, tuned to a dead channel.",
    "Szeth-son-son-Vallano, Truthless of Shinovar, wore white on the day he was to kill a king.",
    "Life before death. Strength before weakness. Journey before destination.", "Always.",
    "There's some good in this world, and it's worth fighting for.", "I am a stick.", 
    "We are not amused.", "Let the wild rumpus start!", "I read therefore I am.",
    "A mind needs books as a sword needs a whetstone.", "So it goes.", 
    "We accept the love we think we deserve.", "Stay gold, Ponyboy.", 
    "I took a deep breath and listened to the old brag of my heart.",
    "Whatever our souls are made of, his and mine are the same.",
    "Tomorrow is always fresh, with no mistakes in it yet.", "Fairy tales are more than true.",
    "I love you past the moon and miss you beyond the stars.",
    "I declare after all there is no enjoyment like reading!",
    "The scar had not pained Harry for nineteen years. All was well.", "He loved Big Brother.",
    "It does not do to dwell on dreams and forget to live.",
    "I am I plus my surroundings; and if I do not preserve the latter, I do not preserve myself.",
    "Forty-two.", "So long, and thanks for all the fish.", "Beware; for I am fearless, and therefore powerful.",
    "It's a poor sort of memory that only works backwards.", "Off with their heads!",
    "Curiouser and curiouser!", "Some pig.", "Where's Papa going with that ax?",
    "I am the Lorax. I speak for the trees.", "Timshel.", "Gatsby believed in the green light.",
    "I like large parties. They're so intimate.", "We were the people who were not in the papers.",
    "Who controls the past controls the future.", "War is peace. Freedom is slavery. Ignorance is strength.",
    "I have always depended on the kindness of strangers.", "A screaming comes across the sky.",
    "Mother died today.", "Once upon a time there was a Martian named Valentine Michael Smith.",
    "The ships hung in the sky in much the same way that bricks don't.",
    "If you want to know what a man's like, take a good look at how he treats his inferiors.",
    "Things fall apart; the centre cannot hold.", "I would prefer not to.", "April is the cruellest month.",
    "Look on my Works, ye Mighty, and despair!", "Water, water, every where, nor any drop to drink.",
    "O Captain! My Captain!", "Two roads diverged in a yellow wood.",
    "Do not go gentle into that good night.", "Rage, rage against the dying of the light.",
    "Because I could not stop for Death.", "Tread softly because you tread on my dreams.",
    "I sound my barbaric yawp over the roofs of the world.",
    "It was a bright cold day in April, and the clocks were striking thirteen.",
    "Last night I dreamt I went to Manderley again.", "Lolita, light of my life, fire of my loins.",
    "A story has no beginning or end.", "You don't know about me without you have read a book by the name of...",
    "Whether I shall turn out to be the hero of my own life...",
    "Shoot all the bluejays you want, if you can hit 'em, but remember it's a sin to kill a mockingbird.",
    "He was roughly the size of a mountain, and twice as craggy.", "Information wants to be free.",
    "The spice must flow.", "He who controls the spice controls the universe.",
    "I will take the Ring, though I do not know the way.", "Poo-tee-weet?",
    "Every book you've ever read is just a remix of the dictionary.",
    "The man in black fled across the desert, and the backlog followed.", "As you wish.",
    "I am a librarian of Babel.", "Reading: A discount ticket to everywhere.",
    "A room without books is like a body without a soul.", "So many pages, so little time.",
    "The TBR pile is a structural load-bearing pillar.", "One ring to rule them all.", 
    "You shall not pass!", "A wizard is never late.", "Fly, you fools!", 
    "As Gregor Samsa awoke one morning from uneasy dreams...", "Der Besuch der alten Dame.",
    "Milliarden für ein Leben.", "Die Physiker.", "Was alle angeht, können nur alle lösen.",
    "Faust.", "Da steh ich nun, ich armer Tor!", "Das also war des Pudels Kern!",
    "Zwei Seelen wohnen, ach! in meiner Brust.", "Heinrich, mir graut's vor dir.",
    "Die Verwandlung.", "Im Westen nichts Neues.", "All Quiet on the Western Front.", 
    "Der Steppenwolf.", "Siddhartha.", "Die unendliche Geschichte.", "The Neverending Story.",
    "Bastian Balthazar Bux.", "Momo.", "Die grauen Herren.", "Tintenherz.", "Inkheart.",
    "Dustfinger.", "Sebastian Fitzek.", "Der Augensammler.", "Die Therapie.", "Passagier 23.",
    "Der Seelenbrecher.", "Psychothriller.", "Marc-Uwe Kling.", "Die Känguru-Chroniken.",
    "Schnapspralinen?", "Halt mal kurz.", "Mein, Dein, das sind doch bürgerliche Kategorien.",
    "Witzig.", "Asoziales Netzwerk.", "QualityLand.", "Peter Arbeitsloser.", "Fourth Wing.",
    "A dragon without its rider is a tragedy.", "A rider without their dragon is dead.",
    "Violence.", "Xaden Riorson.", "Tairn.", "Iron Flame.", "Harry Potter.", "Mischief managed.",
    "I solemnly swear that I am up to no good.", "Yer a wizard, Harry.", "The boy who lived.",
    "He-Who-Must-Not-Be-Named.", "Dumbledore's Army.", "Percy Jackson.", "Camp Half-Blood.",
    "With great power... comes a great need to take a nap. Wake me up later.", 
    "Look, I didn't want to be a half-blood.", "Hunger Games.", "I volunteer as tribute!",
    "May the odds be ever in your favor.", "The Boy with the Bread.", "Real or not real?",
    "Catching Fire.", "Twilight.", "And so the lion fell in love with the lamb.",
    "What a stupid lamb.", "What a sick, masochistic lion.", "A Court of Thorns and Roses.",
    "To the stars who listen— and the dreams that are answered.", "Hello, Feyre darling.",
    "Velaris.", "The City of Starlight.", "Mistborn.", "There's always another secret.",
    "I am, unfortunately, the Hero of Ages.", "Kelsier.", "Vin.", "Stormlight Archive.",
    "The most important step a man can take. It's not the first one, is it? It's the next one.",
    "Honor is dead, but I'll see what I can do.", "Bridge Four.", "The Name of the Wind.",
    "You may have heard of me.", "Kvothe the Bloodless.", "The Kingkiller Chronicle.",
    "A Song of Ice and Fire.", "When you play the game of thrones, you win or you die.",
    "The Lannisters send their regards.", "The Night's Watch.", "Good Omens.",
    "An angel who did not so much Fall as Saunter Vaguely Downwards.", "Ineffable.",
    "Discworld.", "The Turtle Moves.", "Oook.", 
    "DON'T THINK OF IT AS DYING. JUST THINK OF IT AS LEAVING EARLY TO AVOID THE RUSH.",
    "Granny Weatherwax.", "Vimes' Boots theory of socioeconomic unfairness.",
    "American Gods.", "A town called Lakeside.", "Shadow Moon.", "The Ocean at the End of the Lane.",
    "Coraline.", "Other Mother.", "The Martian.", "I'm gonna have to science the shit out of this.",
    "Mark Watney, Space Pirate.", "Project Hail Mary.", "Amaze!", "Fist my bump!", 
    "Jazz hands.", "Rocky.", "Red Rising.", "Break the chains.", "Hic est lupus, motherfucker.",
    "I am the Reaper.", "Omnis vir lupus.", "The Expanse.", "Doors and corners, kid.",
    "Remember the Cant.", "I am that guy.", "Foundation.", "Psychohistory.", "Hari Seldon.",
    "Violence is the last refuge of the incompetent.", "I, Robot.", "The Three Laws of Robotics.",
    "Neuromancer.", "Snow Crash.", "The Deliverator.", "Hiro Protagonist.", "Cat's Cradle.",
    "Ice-nine.", "Brave New World.", "Soma.", "Fahrenheit 451.", "It was a pleasure to burn.",
    "Slaughterhouse-Five.", "The Catcher in the Rye.", "Phony.", "To Kill a Mockingbird.",
    "Atticus Finch.", "The Great Gatsby.", "Old sport.", "Pride and Prejudice.", "Mr. Darcy.",
    "Jane Eyre.", "Wuthering Heights.", "Heathcliff.", "Moby-Dick.", "The white whale.",
    "Les Misérables.", "Jean Valjean.", "24601.", "The Count of Monte Cristo.", "Wait and hope.",
    "Frankenstein.", "It's alive!", "Dracula.", "I never drink... wine.", "The Picture of Dorian Gray.",
    "The only way to get rid of a temptation is to yield to it.", "Alice's Adventures in Wonderland.",
    "We're all mad here."
  ],
  Audiobook: [
    "Listening at 2x speed.", "The narrator's voice is so soothing.", "Whispersync engaged.",
    "Perfect for the commute.", "Washing dishes while consuming epic fantasy.",
    "Wait, let me rewind 30 seconds.", "Fell asleep, where was I?", "Bluetooth connected.",
    "Can't hear you, currently fighting a dragon.", "The ultimate multitasking tool.",
    "Listening at 1.5x speed is the optimal way.", "Letting someone else do the reading.",
    "Volume up, world down.", "The voice inside my head isn't mine right now.",
    "This narrator has a ridiculous number of voices.", "GraphicAudio: A Movie in Your Mind.",
    "I sped it up and now everyone sounds like chipmunks.", "Oh no, a different narrator for the sequel...",
    "Earbuds locked in.", "Auditory hallucination.", "Travis Baldree making everything sound cozy.",
    "Michael Kramer and Kate Reading power hour.", "Simon Vance could read me the phone book.",
    "Stephen Fry's voice is liquid gold.", "Jim Dale vs Stephen Fry.", "RC Bray makes sci-fi better.",
    "Ray Porter dropping knowledge.", "Tim Gerard Reynolds taking me to another world.",
    "Luke Daniels bringing the snark.", "Jefferson Mays reading Expanse.", "Roy Dotrice, bless his soul.",
    "Frank Muller.", "George Guidall.", "Scott Brick is brooding again.", 
    "Marc Thompson doing 50 Star Wars voices.", "Audiobook exclusive interview.", 
    "Full cast recording.", "Audible Hope you enjoy.", "This is Audible.", 
    "We hope you have enjoyed this program.", "Chapter 1.", "Prologue.", "Epilogue.", 
    "Narrated by...", "Listening in the dark.", "Listening at the gym.", 
    "Wait, what did he just say?", "I missed the last 5 minutes.", "The sleep timer failed me.",
    "I fell asleep and woke up 3 hours later in the story.", "My commute is too short for this.",
    "Sitting in the driveway to finish the chapter.", "Just one more track.", 
    "My favorite voice actor.", "The accents are incredible.", "The accents are terrible.",
    "Why did they pronounce it like that?", "That's not how you pronounce Hermione.",
    "That's not how you pronounce Coruscant.", "That's not how you pronounce Tar Valon.",
    "The narrator mispronounced the main character's name.", "The production value is insane.",
    "Ambient background noises.", "Sound effects are distracting.", "I love the sound effects.",
    "Listening on a road trip.", "Listening while doing chores.", "Listening while working.",
    "Can't focus on work and listen at the same time.", "Only listen when driving.",
    "The whispersync price was too good.", "Got it on sale.", "Daily Deal.",
    "Used a credit on a 50-hour epic.", "Used a credit on a 3-hour novella.",
    "Returning this one.", "The sample sounded good...", "I need to look at the map.",
    "Where is the PDF?", "The accompanying PDF is missing.", 
    "I can't spell any of the character's names.", "Wait, it's spelled like THAT?",
    "I thought his name was Kaladin, not Kalladin.", "Jasnah or Yasnah?",
    "Sando makes the miles fly by.", "Wheel of Time takes a year to listen.",
    "Malazan on audio is hardcore.", "Listening to memoirs.", "Celebrity reading their own book.",
    "David Sedaris reading his own stuff.", "Trevor Noah's accents.", 
    "Michelle Obama's soothing voice.", "Matthew McConaughey saying 'Alright, alright, alright'.",
    "Can't listen to nonfiction on audio.", "Can only listen to nonfiction on audio.",
    "Fiction is for audio, nonfiction for print.", "Speed up for boring parts.",
    "Slow down for the good parts.", "My library app keeps crashing.", "Libby delivery!",
    "Hoopla borrow limit reached.", "Wait, is this abridged?!", "Don't talk to me, I'm at the climax.",
    "Is he doing a Scottish accent for a space marine?", "The narrator's female voices are... an experience.",
    "Statement begins.", "Statement ends.", "Ceaseless Watcher, turn your gaze upon this wretched thing.",
    "The Eye.", "Martin!!!", "The Magnus Archives.", "Jonah Magnus.", "The Web.",
    "And now, the weather.", "Welcome to Night Vale.", "Do not approach the Dog Park.",
    "Cecil Palmer.", "Carlos the Scientist.", "All hail the mighty Glow Cloud.",
    "The Bobiverse.", "The Bobs.", "Homer.", "Howard.", "Riker.", "Bill.", "Guppi.",
    "Dungeon Crawler Carl.", "God dammit, Donut!", "New Achievement!", "Glurp glurp.",
    "Mongo is appalled!", "Princess Donut the Queen Anne Chonk.", "Reward: A dirty look.",
    "Sound Booth Theater.", "Jeff Hays is a vocal chameleon.", "The Sandman audio drama is amazing.",
    "James McAvoy voicing Dream.", "Kat Dennings voicing Death.", "Full cast audio production.",
    "Binaural audio.", "Please wear headphones for the best experience.",
    "The BBC full cast adaptation.", "World War Z unabridged.",
    "Mark Hamill voicing a zombie survivor.", "Max Brooks.", "The Lord of the Rings read by Andy Serkis.",
    "Gollum is reading me a story.", "Stephen Fry's Mythos.", "Neil Gaiman reading his own work.",
    "Gaiman's velvety voice.", "Born a Crime on audio.", "Trevor Noah's mother.",
    "The Dutch House read by Tom Hanks.", "Lincoln in the Bardo.", "166 different narrators.",
    "Daisy Jones & The Six.", "Documentary style audiobook.",
    "The Martian read by RC Bray (RIP original version).", "The Martian read by Wil Wheaton.",
    "Project Hail Mary read by Ray Porter.", "Jazz hands (Rocky's chords playing).",
    "Amaze, amaze, amaze!", "The Hitchhiker's Guide read by Stephen Fry.",
    "Martin Freeman reading the sequels.", "Harry Potter read by Jim Dale (Grammy winner).",
    "Harry Potter read by Stephen Fry (The superior version).", "Audie Award winner.",
    "Earphones Award.", "AudioFile Magazine.", "1.0x speed is for cowards.",
    "3.0x speed is for psychopaths.", "Listening while walking the dog.",
    "The dog walked 3 extra miles today.", "Fell asleep and the audiobook played for 8 hours.",
    "Narrator breathing heavily.", "I can hear the narrator swallowing.", "Lip smacks in the recording.",
    "Bad audio mastering.", "The volume levels are all over the place.",
    "I have to turn it up for dialogue and down for explosions.", "The music between chapters is too loud.",
    "Why is there music playing over the reading?", "Sound effects masking the words.",
    "An absolute auditory delight.", "The voice acting elevated the material.",
    "I wouldn't have liked the book if I read it, but the audio was great.",
    "Can't read print anymore, only audio.", "Audiobooks are real reading.", "Is listening reading?",
    "Yes, it counts.", "Whispersync for Voice.", "Immersion reading.", "Scribd.", "Storytel.",
    "Audible Originals.", "Free podcast feed.", "Spotify audiobooks.", "Serial podcast.",
    "S-Town.", "My Favorite Murder.", "Stay sexy and don't get murdered.", "Sword and Scale.",
    "Lore podcast.", "Aaron Mahnke's voice.", "I'm Aaron Mahnke, and this is Lore.",
    "Dan Carlin's Hardcore History.", "A 6-hour podcast episode.", "Age of Illusion.",
    "The podcast intro is 5 minutes long.", "Skipping the ads.", "Use code PODCAST for a free trial.",
    "Squarespace.", "MeUndies.", "Casper Mattress.", "This episode is brought to you by...",
    "Patreon exclusive episode.", "Bonus content.", "Outtakes at the end of the recording.",
    "The narrator bursting out laughing.", "Blooper reel.", "The post-credits interview.",
    "A conversation with the author.", "Author's note read by the author."
  ],
  "Visual Novel": [
    "El Psy Kongroo.", "Tuturu~", "I am mad scientist, it's so cool!", "People die if they are killed.",
    "The archer class really is made up of archers.", "Just because you're correct doesn't mean you're right.",
    "Trace on.", "Unlimited Blade Works.", "When the seagulls cry.", "Without love, it cannot be seen.",
    "Ushiromiya Battler, I'm going to tear you apart!", "Dango Daikazoku.", "A body has been discovered!",
    "Upupupu~", "It's punishment time!", "No, that's wrong!", "Allow me to cut through those words!",
    "Sore wa chigau yo!", "Just Monika.", "I gently open the door...",
    "Every day, I imagine a future where I can be with you.", "This chair. This chair. This chair.",
    "Nanaya grindset.", "Defenseless.", "KIMI TO ISSHO GA ICHIBAN.", "Shirou, do you have enough swords in stock?",
    "Rejoice, boy. Your wish will finally come true.", "I'll destroy that screwed up illusion of yours!",
    "Ahaha.wav", "Nipah~", "Wakarimasu.", "The golden witch.", "Truth is subjective.",
    "It's a trick, magic isn't real.", "Blue truth.", "Red truth.", "Gold truth.", "Ougon Musou Kyoku.",
    "Higurashi When They Cry.", "Umineko When They Cry.", "Ciconia When They Cry.",
    "Muv-Luv Alternative broke me.", "CHOMP.", "PTSD simulator.", "The visual novel medium is literature.",
    "Please read the VN.", "The anime adaptation ruined it.", "Skipping the slice of life.",
    "Auto-read on.", "Skip read text on.", "Save scumming for the good ending.", "Following a walkthrough.",
    "I don't have time for bad endings.", "100% CG completion.", "The soundtrack is a banger.",
    "Key magic.", "Jun Maeda made me cry.", "Kinoko Nasu's worldbuilding.", "Ryukishi07's faces.",
    "Uchikoshi twists.", "Zero Escape.", "My motives are complex.", "Life is simply unfair, don't you think?",
    "Funyarinpa.", "I am Zero.", "Seek a way out.", "Danganronpa.", "Hope vs Despair.",
    "Nagito is crazy.", "Kokichi did nothing wrong.", "Ace Attorney.", "OBJECTION!", "HOLD IT!",
    "TAKE THAT!", "Updated autopsy report.", "The miracle never happen.", "Steins;Gate.",
    "I failed, I failed, I failed.", "Kurisu is best girl.", "Mayuri's watch stopped.",
    "Clannad.", "Tomoya and Nagisa.", "Ushio...", "Fate/stay night.", "Saber route.", "Rin route.",
    "Sakura route.", "Heaven's Feel.", "Tsukihime.", "Tsukihime remake.", "There is no Tsukihime anime.",
    "Witch on the Holy Night.", "Mahoyo.", "White Album 2.", "Todokanai Koi.", "Saya no Uta.",
    "Meat vision.", "Subarashiki Hibi.", "Down the rabbit hole.", "Live, live, live!",
    "G-senjou no Maou.", "Dies irae.", "Atri: My Dear Moments.", "Nekopara.", "Aokana.",
    "Grisaia.", "Fruits of Grisaia.", "Juicy Yuuji.", "Katawa Shoujo.", "Hisao's heart.",
    "Emi's lemons.", "Hanako's bacon.", "Lilly's tea.", "Rin's art.", "Shizune's chess.",
    "Kenji's conspiracy theories.", "Feminist conspiracy!", "Visual novels are games.",
    "Visual novels aren't games.", "Press space to continue.", "Reading at 3 AM.",
    "Why is there a locked route?", "Playing purely for the plot.", "Muv-Luv Extra was just a prank.",
    "A bad end is just a stepping stone.", "Clear file unlocked.",
    "Founder's Pass.", "Eternum server is online.", "Orion.", "Who needs reality anyway?",
    "DIK or C*CK?", "Envy.", "Burgmeister.", "Being a Dik.", "Summertime Saga.", "Captain Terry.",
    "Roxxy.", "Jenny.", "Leap of faith.", "Trust the process.", "Rendered in Ren'Py.",
    "Press space to skip to the good parts.", "Patrons get the update first.",
    "Wait 3 months for the next chapter.", "Checking the changelog.", "Maxing out stats before the next event.",
    "Unlocking the secret gallery.", "Hybrid gameplay.", "Point and click adventures.",
    "Almost Christmas means it wasn't Christmas!", "The parrot on the witness stand.",
    "Cross-examining a walkie-talkie.", "A forged piece of evidence?", "I'm fine! (Maya)",
    "Foolish fool who foolishly dreams of foolish dreams.", "Von Karma's penalty.",
    "Edgeworth's updated autopsy report.", "Gumshoe's salary cut.", "Pursuit - Cornered.",
    "Not guilty!", "Guilty!", "V3's ending was a masterpiece.", "V3's ending was trash.",
    "Did you know that Bungee Gum possesses the properties of both rubber and gum? Wait, wrong medium.",
    "Kamukura Kamukura Yass Queen.", "Meat on the bone.", "On the meat bone?", "Bone the meat on.",
    "The ultimate despair.", "The ultimate hope.", "Makoto Naegi's ahoge.", "Hajime's orange juice.",
    "Chiaki's gaming skills.", "Time to mix drinks and change lives.", "A regular sized beer.",
    "Welcome to Valhalla.", "Dorothy's existential dread.", "The best bartender in Glitch City.",
    "Jill Stingray.", "Rad Shiba.", "Every day is great at your Junes!", 
    "Whoops, Persona is a game, but it has VN elements.", "Social links maxed.",
    "Nine hours, nine persons, nine doors.", "Virtue's Last Reward.", "Zero Time Dilemma.",
    "A snail.", "Complex motives.", "Phi's jumps.", "Sigma's voice.", "Luna's smile.",
    "K's armor.", "To the moon.", "Grab my hand, River.", "Finding Paradise.", "Impostor Factory.",
    "Slay the Princess.", "The smitten.", "The pristine blade.", "The narrator is lying.",
    "You are on a path in the woods.", "Look at this photograph.", "I'm not a furry, but...",
    "Kizuna AI in my VN?", "The true route unlocks after completing everything.",
    "Only 50 more hours to the true ending.", "A 100-hour visual novel.", "I got the worst ending first.",
    "Bad End 14.", "Taiga Dojo.", "Iluya's castle.", "Sella and Leysritt.", "Fate Grand Order is a VN... physically.",
    "Gacha salt.", "Lostbelt.", "Singularity.", "LB6 was essentially a full VN."
  ],
  Movie: [
    "I am your father.", "May the Force be with you.", "I'll be back.", "You're gonna need a bigger boat.",
    "The first rule of Fight Club is...", "There's no place like home.", "Life is like a box of chocolates.",
    "Here's looking at you, kid.", "E.T. phone home.", "To infinity and beyond!", "I'm the king of the world!",
    "Houston, we have a problem.", "There's no crying in baseball!", "You can't handle the truth!",
    "I see dead people.", "My precious.", "Why so serious?", "I am Iron Man.", "Avengers, assemble.",
    "Say hello to my little friend!", "I'm gonna make him an offer he can't refuse.",
    "Frankly, my dear, I don't give a damn.", "Toto, I've a feeling we're not in Kansas anymore.",
    "Show me the money!", "You talkin' to me?", "Roads? Where we're going, we don't need roads.",
    "Keep your friends close, but your enemies closer.", "I completely agree.",
    "Do, or do not. There is no try.", "Welcome to Jurassic Park.",
    "I am serious. And don't call me Shirley.",
    "As far back as I can remember, I always wanted to be a gangster.",
    "It's not a loop, it's a spiral.", "Choose life.", "I'll have what she's having.",
    "Hasta la vista, baby.", "Yippee-ki-yay, motherfucker.", "I feel the need - the need for speed.",
    "I am Groot.", "Wakanda Forever.", "I can do this all day.", "We're in the endgame now.",
    "I love you 3000.", "That's my secret, Cap. I'm always angry.", "I am inevitable.",
    "I am Batman.", "Some men just want to watch the world burn.", "The things you own end up owning you.",
    "I don't know who you are, but I will find you and I will kill you.", "I drink your milkshake!",
    "First rule of leadership: everything is your fault.", "Get busy living, or get busy dying.",
    "Conan! What is best in life?", "To crush your enemies, see them driven before you, and to hear the lamentation of their women.",
    "I've seen things you people wouldn't believe.", "All those moments will be lost in time, like tears in rain.",
    "Hello there.", "General Kenobi.", "It's over, Anakin! I have the high ground!",
    "I don't like sand.", "This is where the fun begins.", "Another happy landing.",
    "A surprise to be sure, but a welcome one.", "I love democracy.", "I am the Senate.",
    "Not just the men, but the women and the children too.", "So uncivilized.",
    "Hello, my name is Inigo Montoya. You killed my father. Prepare to die.", "Inconceivable!",
    "As you wish.", "There's no place like home.", "We're gonna need a bigger boat.",
    "I'll be back.", "I see dead people.", "My precious.", "Houston, we have a problem.",
    "To infinity and beyond!", "I am Iron Man.", "Avengers, assemble.", "Why so serious?",
    "Say hello to my little friend!", "You can't handle the truth!", "I'm the king of the world!",
    "Here's looking at you, kid.", "May the Force be with you.", "I am your father.",
    "E.T. phone home.", "Life is like a box of chocolates.", "There's no crying in baseball!",
    "I'm gonna make him an offer he can't refuse.", "You talkin' to me?",
    "Roads? Where we're going, we don't need roads.", "Welcome to Jurassic Park.",
    "I drink your milkshake!", "Get busy living, or get busy dying.",
    "I've seen things you people wouldn't believe.", "Tears in rain.", "It's not a loop, it's a spiral.",
    "Inception noise (BWAHHH).", "Absolute cinema.", "Kino.", "Matinée.", "Box office hit.",
    "Flop era.", "Cult classic.", "Oscar bait.", "Hidden gem.", "Criterion collection.",
    "Director's cut.", "The Snyder Cut.", "Post-credits scene.", "We live in a twilight world.",
    "And there are no friends at dusk.", "It's Morbin' time.", "I am McLovin.",
    "I am serious, and don't call me Shirley.", "You sit on a throne of lies.",
    "What's in the box?!", "You met me at a very strange time in my life.",
    "Just keep swimming.", "To infinity and beyond!", "I am Groot.", "I volunteer as tribute!",
    "May the odds be ever in your favor.", "I am the captain now.", "Look at me.",
    "Are you not entertained?", "I am Maximus Decimus Meridius.", "What we do in life echoes in eternity.",
    "They may take our lives, but they'll never take our freedom!", "I drink your milkshake!",
    "I abandoned my child!", "I'm mad as hell, and I'm not going to take this anymore!",
    "You tear me apart, Lisa!", "Oh hi Mark.", "I did not hit her, I did not.", "Anyway, how is your sex life?",
    "The room is a masterpiece.", "Tommy Wiseau is a genius.", "Spoon!", "I am the danger.",
    "A boy's best friend is his mother.", "They're here.", "A census taker once tried to test me.",
    "Fava beans and a nice Chianti.", "It puts the lotion on its skin.", "Here's Johnny!",
    "Redrum.", "All work and no play makes Jack a dull boy.", "You're tearing me apart!",
    "You either die a hero, or you live long enough to see yourself become the villain.",
    "It's not who I am underneath, but what I do that defines me.", "Swear to me!",
    "Where is she?!", "I am the night.", "I am Vengeance.", "The Batman.",
    "I am Iron Man.", "I am... inevitable.", "And I... am... Iron Man.", "Mr. Stark, I don't feel so good.",
    "I love you 3000.", "Wakanda Forever.", "I can do this all day.", "On your left.",
    "Avengers... assemble.", "That's America's ass.", "Bring me Thanos!", "I am Groot.",
    "We are Groot.", "I'm Mary Poppins, y'all!", "I have been falling for 30 minutes!",
    "Mew meow.", "Shrek is love, Shrek is life.", "Get out of my swamp!", "Ogres are like onions.",
    "Donkeys!", "Do the roar.", "That'll do, Donkey. That'll do.", "I'm a real boy!",
    "Hakuna Matata.", "Long live the king.", "Remember who you are.", "To infinity and beyond!",
    "You are a sad, strange little man.", "There's a snake in my boot!", "Reach for the sky!"
  ],
  Series: [
    "Winter is coming.", "I am the one who knocks.", "Yeah, Mr. White! Yeah, science!", "Pivot!",
    "That's what she said.", "We have to go back!", "It's not a lie if you believe it.",
    "Clear eyes, full hearts, can't lose.", "Bazinga.", "How you doin'?", "The truth is out there.",
    "Trust no one.", "D'oh!", "I've made a huge mistake.", "There's always money in the banana stand.",
    "Six seasons and a movie.", "Cool. Cool cool cool.", "Treat yo' self.", "Omar strollin'.",
    "It's a show about nothing.", "Wubba lubba dub dub!", "Title of your sex tape.",
    "No soup for you!", "Bears, beets, Battlestar Galactica.", "A Lannister always pays his debts.",
    "Troy and Abed in the morning!", "I'm Dr. Who?", "Live long and prosper.", "Space, the final frontier.",
    "Make it so.", "Tea, Earl Grey, hot.", "Resistance is futile.", "These are their stories. (DUN DUN)",
    "Is mayonnaise an instrument?", "I'm not supersticious, but I am a little stitious.",
    "Identity theft is not a joke, Jim!", "Did I do that?", "We were on a break!",
    "Smelly cat, smelly cat.", "Could I BE any more...", "Yada yada yada.",
    "Not that there's anything wrong with that.", "Hello, Newman.", "Serenity now!",
    "The sea was angry that day, my friends.", "A show about nothing.", "Norm!", "Suit up!",
    "Legen—wait for it—dary!", "Have you met Ted?", "The mother of dragons.",
    "You know nothing, Jon Snow.", "Chaos is a ladder.", "I drink and I know things.",
    "Valar morghulis.", "Hold the door.", "Shame. Shame. Shame.", "The North remembers.",
    "Say my name.", "I am not in danger, Skyler. I am the danger.", "Tread lightly.",
    "Better call Saul!", "It's all good, man.", "Cowabunga!", "Eat my shorts.", "Excellent...",
    "D'oh!", "The truth is out there.", "I want to believe.", "Don't blink.",
    "Wibbly wobbly, timey wimey.", "Allons-y!", "Geronimo!", "Bow ties are cool.",
    "Exterminate!", "Delete!", "You son of a bitch, I'm in.", "Pickle Rick!",
    "I turned myself into a pickle, Morty!", "To be fair, you have to have a very high IQ...",
    "Oh my god, they killed Kenny!", "Respect my authoritah!", "Bite my shiny metal ass.",
    "Good news, everyone!", "Shut up and take my money!",
    "I'm going to build my own theme park! With blackjack! And hookers!", "Phrasing!",
    "Danger zone!", "I am the danger.", "In the criminal justice system...", "Dun dun.",
    "Previously on...", "Next time on...", "To be continued...", "Cancelled after one season.",
    "Netflix adaptation.", "Binge-watching all weekend.", "Just one more episode.",
    "Skipping intro.", "Don't skip the intro!", "The filler arc.", "The beach episode.",
    "The clip show.", "The musical episode.", "The bottle episode.", "The one with the...",
    "The truth is out there, but so are lies.", "I declare bankruptcy!", "Fact: bears eat beets.",
    "Sometimes I'll start a sentence, and I don't even know where it's going.", "Are we having fun yet?",
    "All the information is on the task.", "Your time starts now.", "Little Alex Horne!",
    "Taskmaster's assistant.", "Five points to Gryffindor... wait, wrong show.", 
    "I've been here the whole time.", "Make some noise!", "Game Changer.", "Um, actually...",
    "Get in the comments!", "Brennan Lee Mulligan's rant.", "Dropout TV.", "The points don't matter.",
    "Whose Line Is It Anyway?", "Things you can say about your boat but not your partner.",
    "It's a me, Mario (Game Changer).", "Survivor.", "The tribe has spoken.", "Outwit, outplay, outlast.",
    "Immunity idol.", "The Amazing Race.", "Phil Keoghan's eyebrows.", "Jeopardy!",
    "I'll take 'Potpourri' for $400, Alex.", "Daily Double.", "Wheel of Fortune.",
    "I'd like to buy a vowel.", "Come on down!", "The Price is Right.", "Plinko.",
    "Big Brother.", "Expect the unexpected.", "First Dates.", "Love Island.", "I've got a text!",
    "Coupling up.", "The Great British Bake Off.", "Paul Hollywood's handshake.", "Soggy bottom.",
    "On your marks, get set, BAKE!", "MasterChef.", "This is raw!", "Idiot sandwich.",
    "Hell's Kitchen.", "It's raw, you donkey!", "Kitchen Nightmares.", "Shark Tank.",
    "And for that reason, I'm out.", "Dragons' Den.", "RuPaul's Drag Race.", "Lip sync for your life.",
    "Sashay away.", "Shantay you stay.", "Reading is fundamental.", "The libraries are open.",
    "Doctor Who.", "Time and Relative Dimension in Space.", "Sonic screwdriver.",
    "The TARDIS is bigger on the inside.", "Daleks.", "Cybermen.", "Weeping Angels.",
    "Sherlock.", "The game is on.", "Mind palace.", "I am a high-functioning sociopath.",
    "Stranger Things.", "The Upside Down.", "Demogorgon.", "Eleven's eggos.", "Friends don't lie.",
    "Black Mirror.", "What if phones, but too much?", "San Junipero.", "The Crown.",
    "Succession.", "You can't make a Tomlette without breaking some Greggs.", "L to the OG.",
    "Boar on the floor.", "The Sopranos.", "Gabagool.", "Woke up this morning, got yourself a gun.",
    "Don't stop believin'.", "Mad Men.", "It's toasted.", "Not great, Bob!", "The Wire.",
    "Omar comin'!", "Shiiiiiiiiiiit.", "All in the game.", "Twin Peaks.", "Damn fine cup of coffee.",
    "The owls are not what they seem.", "Fire walk with me.", "Lost.", "The Hatch.",
    "We have to go back, Kate!", "4 8 15 16 23 42.", "Scrubs.", "EAGLE!", "Where do you think we are?",
    "The IT Crowd.", "Have you tried turning it off and on again?", "Did you see that ludicrous display last night?",
    "A fire? At a sea parks?", "Fawlty Towers.", "Don't mention the war.", "Blackadder.",
    "I have a cunning plan.", "Peep Show.", "Four naan, Jeremy? That's insane.", "Super hans.",
    "Fleabag.", "It'll pass.", "The priest.", "Looking directly at the camera.", "The Bear.",
    "Yes chef!", "Corner!", "Behind!", "Cousin!", "Every second counts.", "The Mandalorian.",
    "This is the way.", "I have spoken.", "Grogu.", "Andor.", "One way out!",
    "I burn my life to make a sunrise that I know I'll never see.", "Ted Lasso.", "Believe.",
    "Be a goldfish.", "Football is life.", "Severance.", "Please enjoy each fact equally.",
    "Praise Kier.", "Waffle party.", "The office.", "The Dundies.", "Threat Level Midnight.",
    "Scott's Tots.", "Parks and Recreation.", "Lil Sebastian.", "Cones of Dunshire.",
    "Galentine's Day.", "Arrested Development.", "I'm a monster!", "Her?", "Annyong.",
    "Bob's Burgers.", "Burger of the Day.", "Alriiiiight.", "Uhhhhhhhhhhh.", "King of the Hill.",
    "That boy ain't right.", "Pocket sand!", "Propane and propane accessories.", "The Simpsons.",
    "Mmm... donuts.", "Steamed hams.", "Aurora Borealis?", "Futurama.", "Death by snu snu.",
    "To shreds, you say?", "Avatar: The Last Airbender.", "My cabbages!", "That's rough, buddy.",
    "There is no war in Ba Sing Se.", "Everything changed when the Fire Nation attacked.",
    "Leaves from the vine.", "Boomerang! You do always come back!", "Bojack Horseman.",
    "What are YOU doing here?", "Back in the 90s...", "Sad horse show.", "It gets easier. Every day it gets a little easier."
  ],
  Manga: [
    "I am the hope of the universe.", "Omae wa mou shindeiru.", "I will take a potato chip... and eat it!",
    "Equivalent exchange.", "Bankai.", "Domain Expansion.", "I'm gonna be King of the Pirates!",
    "Stand proud, you are strong.", "Nah, I'd win.", "It was me, Dio!", "I reject my humanity, JoJo!",
    "Yare yare daze.", "What a beautiful Duwang.", "People's dreams... HAVE NO END!",
    "The One Piece is real!", "This world is rotten.", "All according to keikaku.",
    "(Translator's note: keikaku means plan)", "Can we get much higher?", "I want to live!",
    "Nothing happened.", "Dattebayo!", "Give up on your dreams and die.", "Tatakae.",
    "I keep moving forward, until my enemies are destroyed.", "Aizen's chair.",
    "Since when were you under the impression that I wasn't using Kyoka Suigetsu?",
    "You spin me right round, baby, right round.", "Guts' theme intensifies.", "He laughed.",
    "GOMU GOMU NO...", "Gear Second.", "Gear Fourth.", "Gear Fifth.", "Kaizoku ou ni ore wa naru!",
    "I'm gonna be Hokage!", "Believe it!", "Rasengan!", "Chidori!", "Talk no Jutsu.",
    "I will save you, Sasuke!", "Getsuga Tensho!", "I am a Quincy.", "Hollowfication.",
    "Kamehameha!", "It's over 9000!", "Super Saiyan.", "Ultra Instinct.", "Frieza!",
    "Plus Ultra!", "Detroit Smash!", "One For All.", "Half-cold, half-hot.",
    "It's fine now. Why? Because I am here!", "Elric brothers.", "Fullmetal Alchemist.",
    "Ed...ward...", "It's a terrible day for rain.", "Gintama.", "Justaway.",
    "Neo Armstrong Cyclone Jet Armstrong Cannon.", "Neo Tokyo is about to E.X.P.L.O.D.E.",
    "Tetsuo!", "Kaneda!", "Stand Name:", "Stand Master:", "Ora ora ora!", "Muda muda muda!",
    "Za Warudo!", "King Crimson just works.", "I Giorno Giovanna have a dream.",
    "Arigato, Gyro.", "Pizza Mozzarella.", "Hunter x Hunter.", "Hiatus x Hiatus.", "Gon's hair.",
    "Bungee Gum possesses the properties of both rubber and gum.", "Chimera Ant arc.", "Meruem.",
    "Komugi, are you still there?", "Death Note.", "Shinigami love apples.", "I am L.", "I am Kira.",
    "Attack on Titan.", "Shinzou wo Sasageyo!", "Levi's beyblade.", "Eren did nothing wrong.",
    "Rumbling, rumbling, it's coming!", "Tenoi.", "Kagura Bachi.", "Enough time has passed.",
    "Peak fiction.", "Read the manga.", "The anime is catching up.", "Filler arc.", "Scanlations.",
    "Raw chapters.", "The translations are out.", "Waiting for the new chapter.",
    "Weekly Shonen Jump.", "Mangaka needs a break.", "Hiatus.", "Axe'd.", "Rushed ending.",
    "It peaked in the Golden Age arc.", "You are my special.",
    "Are you the strongest because you're Satoru Gojo?", "Or are you Satoru Gojo because you're the strongest?",
    "Throughout Heaven and Earth, I alone am the honored one.", "Crying over 2D characters.",
    "Griffith did nothing wrong.", "Struggle, Contend, Survive.", "The Eclipse.", 
    "Don't put your grasses on.", "You have no enemies.", "A true warrior needs no sword.",
    "Thorfinn's character development.", "Look at me, the monster inside me has grown this large.",
    "Johan Liebert.", "Dear God, tinkle tinkle hoy.", "Oyasumi Punpun.", "Depression in manga form.",
    "What's 1000 minus 7?", "Tokyo Ghoul.", "Unravel playing in the background.",
    "I love a woman who can kick my ass.", "Chainsaw Man.", "Bark for Makima.", "Aki's snowball fight.",
    "Power's Nobel Prize.", "Fujimoto's wild ride.", "Fire Punch.", "Kino.", "Become Fire Punch.",
    "Aura, kill yourself.", "Frieren.", "Himmel the Hero.", "It's been 80 years since the hero's death.",
    "Magic that creates fields of flowers.", "Zoltraak.", "Spy x Family.", "Waku waku!",
    "Anya's smug face.", "Elegant!", "Demon Slayer.", "Breathing techniques.",
    "Water Breathing, First Form.", "Muzan Jackson.", "Rengoku's donut.", "Set your heart ablaze.",
    "My Dress-Up Darling.", "Cosplay making.", "Komi Can't Communicate.", "Tadano is a chad.",
    "Kaguya-sama.", "Love is War.", "O kawaii koto.", "Shirogane's sleep deprivation.", "Chika dance.",
    "Oshi no Ko.", "Star eyes.", "Ai's lie.", "Baking soda genius child actor.", "Nana.", "Trapnest.",
    "BLAST.", "Yotsuba&!", "Enjoy everything.", "Asadora!", "20th Century Boys.", "Tomodachi.",
    "Kenji's song.", "Pluto.", "Naoki Urasawa's genius.", "Vagabond.", "Miyamoto Musashi.",
    "Farming arc.", "Invincible under the sun.", "Slam Dunk.", "Do you like basketball?",
    "I'm a genius!", "The left hand is just for support.", "Haikyuu!!", "Fly!", "Rolling Thunder!",
    "Kuruko's Basketball.", "The Generation of Miracles.", "Zone.", "Blue Lock.", "Egoist.",
    "I am a striker.", "Devour them.", "Hajime no Ippo.", "Dempsey Roll.", "Wind Breaker.",
    "Bouncer.", "GTO.", "Great Teacher Onizuka.", "My Cresta!", "Mob Psycho 100.", "100% stress.",
    "Body Improvement Club.", "Fight on!", "One Punch Man.", 
    "100 push-ups, 100 sit-ups, 100 squats, and a 10km run.", "Ok.", "Murata's art is god-tier.",
    "The legendary double-page spread.", "Gantz.", "Black sphere.", "Kurono.", "Inuyasha.",
    "Kagome!", "SIT!", "Sailor Moon.", "In the name of the moon, I'll punish you!", "Cardcaptor Sakura.",
    "Release!", "Fruits Basket.", "Year of the Cat.", "Tohru's kindness.", "Ouran High School Host Club.",
    "Kiss kiss fall in love.", "Damn rich people.", "Rose of Versailles.", "Oscar.", "Uzumaki.",
    "The spiral.", "Junji Ito's horror.", "This hole was made for me.", "Gyo.", "Tomie.",
    "Devilman Crybaby.", "Akira.", "Tetsuo's bike.", "Ghost in the Shell.", "Major Motoko Kusanagi.",
    "Stand Alone Complex.", "Appleseed.", "Gundam.", "Char Aznable.", "Three times faster.",
    "Drop a colony.", "Evangelion.", "Get in the robot, Shinji.", "I mustn't run away.",
    "Congratulations!", "You can (not) redo.", "Cowboy Bebop.", "See you space cowboy.",
    "Whatever happens, happens.", "Trigun.", "Vash the Stampede.", "Love and peace!",
    "Hellsing.", "Alucard.", "Bitches love cannons.", "Black Lagoon.", "Two Hands.", "Revy."
  ],
  Comic: [
    "With great power comes great responsibility.", "I am Batman.", "Avengers assemble!",
    "Up, up and away!", "It's clobberin' time!", "Snikt!", "In brightest day, in blackest night.",
    "HULK SMASH!", "Imperius Rex!", "I'm the best there is at what I do.", "To me, my X-Men.",
    "Who watches the Watchmen?", "I'm not locked in here with you. You're locked in here with me.",
    "We live in a society.", "Because I'm Batman!", "Flame on!", "Shazam!", "BAMF!", "THWIP!",
    "Excelsior!", "Make mine Marvel.", "The Death of Superman.", "Doomsday Clock.",
    "Welcome to the X-Men, hope you survive the experience.", "I am Vengeance. I am the Night.",
    "Some days, you just can't get rid of a bomb.", "Holy bat-tropes, Batman!", "Boy Wonder.",
    "The Dark Knight Returns.", "The Killing Joke.", "All it takes is one bad day.", "I have a plan.",
    "Tower of Babel.", "Crisis on Infinite Earths.", "Flashpoint.", "It was me, Barry!",
    "My name is Barry Allen, and I am the fastest man alive.", "Reverse Flash.", "Speed Force.",
    "Truth, Justice, and the American Way.", "Man of Steel.", "Kneel before Zod!",
    "Look, up in the sky!", "It's a bird, it's a plane!", "Lex Luthor stole forty cakes.",
    "That's as many as four tens.", "And that's terrible.", "Wonder Woman.", "Lasso of Truth.",
    "Themyscira.", "Aquaman talks to fish.", "Outrageous!", "Green Lantern's light!",
    "Beware my power!", "No evil shall escape my sight.", "Let those who worship evil's might...",
    "In blackest day, in brightest night...", "Wait, isn't it the other way around?",
    "Deadpool breaks the fourth wall.", "Chimichangas!", "Maximum Effort.",
    "Spider-Man points at Spider-Man.", "Friendly neighborhood Spider-Man.", "My spider-sense is tingling.",
    "Parker Luck.", "Mary Jane.", "Face it, tiger... you just hit the jackpot!", "Gwen Stacy.",
    "SNAP.", "X-Men, to me!", "Magneto was right.", "Cyclops was right.", "Professor X is a jerk.",
    "Fastball special.", " bub.", "I am Groot.", "I am Steve Rogers.", "Hail Hydra.",
    "Wakanda Forever.", "Fantastic Four.", "First Family.", "Richards!", "Doom demands your attention.",
    "Doom is supreme.", "Kneel before Doom.", "The Illuminati.", "Infinity Gauntlet.",
    "Perfectly balanced, as all things should be.", "I can do this all day.", "Daredevil.",
    "The Man Without Fear.", "Hell's Kitchen.", "Punisher.", "One batch, two batch. Penny and dime.",
    "Spawn.", "Invincible.", "Think, Mark, think!", "The Boys.", "Homelander.", "Diabolical.",
    "Walking Dead.", "Coral!", "Saga.", "Lying cat.", "Graphic novel.",
    "It's not a comic book, it's a graphic novel.", "Read order.", "Reboot.", "Retcon.", "Multiverse.",
    "Earth-616.", "Earth-Prime.", "New 52.", "Rebirth.", "Secret Wars.", "Absolute edition.",
    "Omnibus is too heavy to read.", "Bagged and boarded.", "Variant cover.", "First appearance.",
    "Mint condition.", "CGC 9.8 graded.", "Key issue.", "Why did his cape just disappear in the next panel?",
    "Bless my bagpipes!", "Curse you, Flintheart Glomgold!", "I'm the richest duck in the world.",
    "Money bin diving.", "The Junior Woodchucks Guidebook.", "Uncle Scrooge.", "Donald's temper.",
    "DuckTales, woo-oo!", "Gyro Gearloose's latest invention.", "Magica De Spell.", "The Beagle Boys.",
    "Great snakes!", "Billions of bilious blue blistering barnacles!", "Ten thousand thundering typhoons!",
    "Captain Haddock.", "Snowy the dog.", "Calculus's pendulum.", "By the rings of Saturn!",
    "Asterix and Obelix.", "These Romans are crazy.", "By Toutatis!", "The magic potion.",
    "Falling into the cauldron as a baby.", "Getafix.", "Dogmatix.", "I am not fat!",
    "V for Vendetta.", "Remember, remember, the fifth of November.", "Ideas are bulletproof.",
    "Hellboy.", "Right Hand of Doom.", "Mignola's shadows.", "B.P.R.D.", "Scott Pilgrim.",
    "Level up!", "The power of self-respect.", "I'm in lesbians with you.", "Garfield.",
    "I hate Mondays.", "Where's the lasagna, Jon?", "Calvin and Hobbes.", "Transmogrifier.",
    "Spaceman Spiff.", "Noodle incident.", "Peanuts.", "Good grief.", "Snoopy vs the Red Baron.",
    "The football gag.", "Scorched earth.", "Girls get it done.", "I can do whatever the f**k I want.",
    "Compound V.", "Billy Butcher's accent.", "The Seven.", "The Teenage Mutant Ninja Turtles.",
    "Cowabunga!", "Heroes in a half-shell.", "Turtle power!", "Master Splinter.", "The Shredder.",
    "Pizza time.", "Bone.", "Stupid, stupid rat creatures.", "Quiche!", "Fables.", "Bigby Wolf.",
    "The Sandman.", "I am Hope.", "Dream of the Endless.", "Death's ankh.", "The Corinthian's eyes.",
    "Swamp Thing.", "John Constantine.", "Hellblazer.", "Sin City.", "The hard goodbye.",
    "Yellow bastard.", "Maus.", "Vladek's story.", "Blankets.", "Persepolis.", "Ghost World.",
    "Radiant Black.", "The Wicked + The Divine.", "Bitch Planet.", "Non-compliant.", "Y: The Last Man.",
    "Ampersand.", "Preacher.", "The Word of God.", "Garth Ennis being Garth Ennis.", "Alan Moore's beard.",
    "Grant Morrison's chaos magic.", "Jack Kirby dots.", "Krackle.", "Stan Lee's cameos."
  ]
};

export function getRandomFlavorText(mediaType: string): string {
  const texts = MEDIA_FLAVOR_TEXTS[mediaType] || ["Your entire history, collection, and backlog.", "Where did the time go?", "Cultured tastes.", "To be consumed.", "Ah, a classic."];
  return texts[Math.floor(Math.random() * texts.length)];
}
